### ISSUE TITLE
Executing the awscli throws NullPointerException on subsequent calls after login

### ISSUE THREAD

**Issue by joewitt99** [oktadeveloper/okta-aws-cli-assume-role#100]
When executing the awscli with the following properties:
OKTA_ORG=[okta tenant]
OKTA_AWS_APP_URL=[application url]
OKTA_USERNAME=
OKTA_PASSWORD=
OKTA_AWS_ROLE_TO_ASSUME=

I am prompted to authenticate as expected.  When I execute the awscli a second time I get the following Exception:
Exception in thread "main" java.lang.NullPointerException
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:109
)
        at com.okta.tools.awscli.main(awscli.java:31)

At this point.  From the code there is a check for oktaProfile.isEmpty()
if (session.isPresent() && sessionIsActive(startInstant, session.get()) && oktaProfile.isEmpty())

Since this property is not defined a NullPointerException is thrown.  When I add the property to the config.properties.  The exception goes away and everything works as expected.  Except for logout.

Logout throws the following exception:
Exception in thread "main" java.lang.NullPointerException
    at org.ini4j.BasicProfile.remove(BasicProfile.java:139)
    at com.okta.tools.aws.settings.MultipleProfile.deleteProfile(MultipleProfile.java:47)
    at com.okta.tools.OktaAwsCliAssumeRole.logoutMulti(OktaAwsCliAssumeRole.java:158)
    at com.okta.tools.OktaAwsCliAssumeRole.logoutSession(OktaAwsCliAssumeRole.java:144)
    at com.okta.tools.awscli.main(awscli.java:25)

If I remove the property from the config then logout works, so I am in a catch 22 scenario.

**Comment by andreihava-okta** [comment]
@joewitt99 Thank you for submitting this issue on GitHub as well. As per our internal discussion, we will take a look at this as soon as possible.

CC @AlainODea @smashling @mraible - Issue opened following an internal ticket opened with support by Joe who's an Okta employee.

**Comment by smashling** [comment]
I believe this issue was fixed  in Pull request #96 :bug: NPE on second run with no profile name unless I am misunderstanding the error.

**Comment by joewitt99** [comment]
I pulled the master and built the snapshot and I was able to get past the errors..   Thanks, which will there be a 1.0.1 GA release?

**Comment by mraible** [comment]
I can do one today. It’s automated, so I just need to create a release/tag on GitHub and it auto-publishes with Travis.

**Comment by nbarbettini** [comment]
Thank you @mraible 😄

**Comment by cchristous** [comment]
@mraible looks like the `okta-aws-cli-1.0.1.jar` didn't get uploaded to the [releases](https://github.com/oktadeveloper/okta-aws-cli-assume-role/releases) page

**Comment by mraible** [comment]
I'll upload it now. The automation doesn't add it to the release - that's a manual process. It does auto-upload it to https://packagecloud.io/oktadev/okta-aws-cli-assume-role. Maybe we should add that URL to the README?

**Comment by cchristous** [comment]
Thanks for the link. I think adding that URL to the README is a good idea.
