### ISSUE TITLE
Error Encountered After MFA Prompt

### ISSUE THREAD

**Issue by rp4rk** [oktadeveloper/okta-aws-cli-assume-role#101]
After being prompted for your MFA code, so far having tested both SMS and Google Authenticator, you'll be greeted with an error. Here's a stacktrace:

```
./awscli.command
Username: <my username>
Password: <my password>

Multi-Factor authentication is required. Please select a factor to use.
Factors:
[ 1 ] : Google Authenticator

GOOGLE Token Factor Authentication
Enter 'change factor' to use a different factor
Token:
xxxxxx
Exception in thread "main" java.lang.RuntimeException: You do not have access to AWS through Okta.
Please contact your administrator.
	at com.okta.tools.OktaAwsCliAssumeRole.getSamlResponseForAws(OktaAwsCliAssumeRole.java:358)
	at com.okta.tools.OktaAwsCliAssumeRole.getSamlResponse(OktaAwsCliAssumeRole.java:125)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:111)
	at com.okta.tools.awscli.main(awscli.java:31)
```

Having checked this across multiple users, and accounts, and verifying we do indeed have access to AWS through Okta - my conclusion has to be that this is a bug or regression.

Here are some related issues in the past with similar problems:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/2
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/61

**Comment by smashling** [comment]
This error has come up in the past if the google token was input too late and it expired while attempting to authenticate the token. When this happens, it gets caught in a bad state, and the current workaround is to run ./awscli logout.

**Comment by rp4rk** [comment]
Thanks for the heads up, I'll keep this in mind for when it next occurs and see if it resolves the problem.
