### ISSUE TITLE
Is it working with a second MFA?

### ISSUE THREAD

**Issue by pollosp** [oktadeveloper/okta-aws-cli-assume-role#102]
I have two accounts of AWS one where we always enforce MFA before login to the AWS account and other were we don't enforce it.  I'm using version 1.0.0 and it isn't working with the first case, I'm getting the following error:

```
$ java -classpath .:okta-aws-cli-1.0.0.jar com.okta.tools.awscli help
Username: XXXX
Password:

Multi-Factor authentication is required. Please select a factor to use.
Factors:
[ 1 ] : push
[ 2 ] : Okta Verify
Selection: 1

Push Factor Authentication
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
20111SoHh4CPJ81rmMQ2E1uWLMmKcbvOwZRB9gvM8PTQNSAgkOzei7F
Exception in thread "main" java.lang.RuntimeException: You do not have access to AWS through Okta.
Please contact your administrator.
	at com.okta.tools.OktaAwsCliAssumeRole.getSamlResponseForAws(OktaAwsCliAssumeRole.java:358)
	at com.okta.tools.OktaAwsCliAssumeRole.getSamlResponse(OktaAwsCliAssumeRole.java:125)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:111)
	at com.okta.tools.awscli.main(awscli.java:31)
```

I think it did the first MFA (my account always enforce MFA for OKTA logging from unknown devices) and it didn't tries to do the enforced MFA of the AWS account. 

```
java -classpath .:okta-aws-cli-1.0.0.jar com.okta.tools.awscli help
Username: XXXX
Password:

Multi-Factor authentication is required. Please select a factor to use.
Factors:
[ 1 ] : push
[ 2 ] : Okta Verify
Selection: 1

Push Factor Authentication
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
20111t662lc0F_rQvlvPcibgn1Qh6GUePZVYoxGreSAKbRzHw-5I1za
Auto select role as only one is available : arn:aws:iam::ZZZ:role/OktaAdmins
```
This is the case where we didn't enforce MFA for the AWS account but we are enforcing MFA for the OKTA account (for unknown devices).

**Comment by AlainODea** [comment]
App-level MFA will not work with this tool. It’s not supported by the Okta API. It only works in web browsers right now.

I thought Okta Push worked, but apparently not. Duo Push definitely doesn’t.

Okta Verify (TOTP) should work.

**Comment by AlainODea** [comment]
App-level MFA doesn’t work, but Org-level does.

I used the “Google Authenticator” option to get a TOTP QR Code for MFA. I scanned that with Duo Mobile, but you can scan it with any TOTP app.

**Comment by brasstax** [comment]
Hi Alain,

Do you know if there are eventual plans to support app-level MFA?  If so, and if it will help for tracking purposes, I can open a new issue. I'm running into a similar issue with app-level MFA not working.

Thank you.

**Comment by AlainODea** [comment]
@brasstax I’m not an Okta employee. As a fellow Okta customer. I have heard no specific plans to support app-level MFA. Your account manager may know.

Similar to Duo Push, app-level MFA could be supported by delegating the auth flow to a web browser. My prorities have been shifted off this project, so I won’t be pursuing that, but it would be an exceptional contribution if you know how.

**Comment by brasstax** [comment]
Ahh, my apologies, I thought you were.  I can talk to my account manager and see they recommend I open a new issue entirely.

**Comment by AlainODea** [comment]
Once there is a release based on #109, you should be (in principle at least) able to get this working. If you want this prior to that point, you can build master using maven and try it.

**Comment by AlainODea** [comment]
My colleague pointed out that my solution to this is incomplete. It will not crash on subsequent MFA challenges within the same session (if you set every time or some time lower than the Okta session timeout) when invoking the Amazon Web Services application. You'll need to delete **~/.okta/cookies.properties** if you encounter this. Sorry about that.

**Comment by mlmargotto** [comment]
Hi Guys.
Just to understand if this solution can be applied in our environment.
Our scenario use AWS with MFA (only this app). with browser, we can authenticate (user, pass and MFA) and works. 
But, we need AWSCLI a lot and MFA is required for AWSCLI too.
Any alternative to use browser to authenticate and use this session in AWSCLI commands?.

**Comment by AlainODea** [comment]
This issue discussion has gone off-topic. Consolidating with #25.
