### ISSUE TITLE
Issue with MFA

### ISSUE THREAD

**Issue by ziemowitp** [oktadeveloper/okta-aws-cli-assume-role#106]
Hi,

I enabled MFA on my account and since then I am unable to do anything.  According to Okta, the login was successful.  What I assume I should be getting is the list of accounts and roles to select.  We have multiple linked accounts and roles.  Could it a race issue of some sort?

$ awscli help
Username: xxxxxxx
Password: 

Multi-Factor authentication is required. Please select a factor to use.
Factors:
[ 1 ] : push
[ 2 ] : Okta Verify
Selection: 1

Push Factor Authentication
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Exception in thread "main" java.lang.RuntimeException: You do not have access to AWS through Okta. 
Please contact your administrator.
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAws(OktaSaml.java:54)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:44)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:88)
	at com.okta.tools.awscli.main(awscli.java:33)

**Comment by AlainODea** [comment]
App-level MFA policies are not supported. For details see #25

**Comment by ziemowitp** [comment]
I see.  So just to recap: setting up MFA "Sign On Policy" in individual applications isn't supported.  Thank you.
