### ISSUE TITLE
Doesn't work with external default identity provider

### ISSUE THREAD

**Issue by mozillamonks** [oktadeveloper/okta-aws-cli-assume-role#107]
In our org we use Google as our default idp, and in this situation the CLI tool falls down. In an ideal world it would be good to have another way to perform this style of auth, perhaps by kicking open a browser windows or having a way to open an Okta page and enter a keycode to finish the authentication with the external provider.

If this is already possible, I may be missing it.

**Comment by AlainODea** [comment]
The tool currently doesn't support that.

It's quite involved to change this tool to use a web browser for the auth flow. Adding web browser-based auth would implicitly add support for per-app MFA and Duo Push along with support for external IdPs (assuming they have sufficiently expressive RelayState support).

I'm no longer working on this, but I wanted you to get an answer.

**Comment by AlainODea** [comment]
Once there is a release based on #109, you should be (in principle at least) able to get this working by setting **OKTA_AWS_APP_URL** to your external IdP's URL assuming you have configured or appended the RelayState to it correctly.

**Comment by AlainODea** [comment]
@mozillamonks the v1.0.2 release includes OKTA_BROWSER_AUTH support. That might work for your use case.

**Comment by AlainODea** [comment]
@mozillamonks have you had a chance to try this with OKTA_BROWSER_AUTH?

**Comment by kutchar** [comment]
@mozillamonks were you able to get this to work? We are using GSuite as our default idp for Okta too.

**Comment by kutchar** [comment]
I was able to get this to work pretty much out right out of box using GSuite as the idp.

**Comment by kutchar** [comment]
Here's my config:
```
OKTA_ORG=<My org>.okta.com
OKTA_AWS_APP_URL=<Okta AWS app URL>
OKTA_USERNAME=<My Okta username>
OKTA_BROWSER_AUTH=true
```

**Comment by AlainODea** [comment]
@kutchar am I right in reading that you got this working with pretty much no special configuration? If so, that’s awesome!

**Comment by kutchar** [comment]
@AlainODea yes, it works with the config I posted above. We use GSuite as our Identity Provider for Okta and using this method, awscli launches a Java browser window which allows me to login to Google which in turn logs me into Okta and allows the CLI to start a session. The only minor caveat is that you can only use SMS or Google Authenticator as MFA and not the "Google Prompt" and I believe it's because of a JavaScript issue with Google & Java browser.

**Comment by AlainODea** [comment]
Great. Thank you for confirming, @kutchar :)
