### ISSUE TITLE
Programmatic access to the Okta AWS CLI functionality

### ISSUE THREAD

**Issue by Hervian** [oktadeveloper/okta-aws-cli-assume-role#110]
*Question*

Hi, I want to construct a GUI around the Okta AWS CLI tool. Or rather, around my AWS services and 
accounts, but being an Okta customer, I must use the Okta AWS CLI functionality for login.

Is this possible?

I can add a the project as a dependency to my own Java project using JitPack. But the jar file seem to contain a module-info.class which does not expose any packages. 
This is the furst hurdle, which I can overcome by transforming my own project into a Java 8 project. 
Can you foresee any other problems and do you have plans on making your project be used like a dependency/a library? Right now if feels bit "hackish" to go down this road.

Examples of implemention details that make programmatic usage of the project very difficult:

- Most classes are package private (default class modifier)
- Most classes are final, thereby preventing overriding.
- The main method ends with a System.exit, and this call is not extracted into an overridable instance method.

The only way I can think of is to (somehow) invoke the main method as an external process (thereby preventing shutdown of my GUI on the call to System.exit) and (somehow) hijacking standard in and standard out such as to provide answers to the various questions (username, password and role selection). I do not know if all of this is possible, and if it is, it is very fragile.
The best thing would off course be if the project was slightly changed to accomadate this kind of usage.

Best regards, Anders

**Comment by AlainODea** [comment]
@Hervian this is architected as an application and not a library.

If you're up for it, extracting the library elements into a reusable module would be very useful.

The new **BrowserAuthentication** class is particularly unfriendly for library use, but it could be kept in the app part of the modular separation.

**Comment by AlainODea** [comment]
As for the Java 9 stuff, I bulldozed that into a baseline functioning system, but didn't actually think properly about JPMS in the process at all. If you are experienced with JPMS, cleaning that up would be very welcome as well :)

**Comment by Hervian** [comment]
Thanks, I will try to do some small refactoring with the aim of enabling library usage of the project - and when done create a pull request.

I think my strategy will be as follows:
- Extract credentials login, MFA login, role selection etc into library components, capable of accepting input from the user of the library instead of being "hardcoded" to prompt for input.
- Make credentials be passed around more securily (in a char[] array which will be overwritten once information has been processed perhaps) since when the code is used as a library (and not a short lived process) the objects will be in memory.
- Try to make the module-info expose necessary library components ( am new to Java 9 and must investigate how this works).

When you write "modular separation" are you then talking about Maven modules, or just a logical separation of the code? My approach would be to make the refactoring as simple as possible: The app part will be the main method, which samples library components, much like a user of the library would.

**Comment by AlainODea** [comment]
When I write “modular separation”, I was thinking JPMS modules within this same codebase as a start. Maven modules would be useful later. Only take this as far as you need to for your use case. Someone will come along who wants to depend on the library part externally and they can make the Maven piece happen :)

**Comment by AlainODea** [comment]
@Hervian I think #116 fixes this. Is that correct? If so, can you close this issue?
