### ISSUE TITLE
Change deployment to OSSRH since packagecloud has been disabled

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-aws-cli-assume-role#114]
http://central.sonatype.org/pages/ossrh-guide.html

It'd also be cool to automate the GitHub release process so the following happens:

1. Create a new release locally with Maven. 
2. Release gets created on GitHub. 
3. Release notes include link to download JAR from Maven Central, or uploads JAR to release.

OR:

1. Create a new release on GitHub. 
2. Travis releases to Maven Central.
3. Travis adds a link in the release notes + the JAR as a download.

**Comment by mraible** [comment]
@bdemers Let me know if you have any advice on how to implement this.

**Comment by AlainODea** [comment]
@bdemers this would be useful as there are some merged, but unreleased fixes here and this could streamline that process.

**Comment by AlainODea** [comment]
I'm going to close this for now. If someone is interested in tackling this, it can be reopened.
