### ISSUE TITLE
Add authentication support when using AWS java sdk

### ISSUE THREAD

**Issue by alebaldo** [oktadeveloper/okta-aws-cli-assume-role#115]
Hello, 
I've made some changes to OktaAwsCliAssumeRole class in order to add support for authentication through java sdk.
With these changes the tool can be used with both CLI and java sdk.

I tried to create a PR, but it seems I don't have permission to do so.

Thanks.

**Comment by AlainODea** [comment]
This sounds great 😊

You should be able to make a pull request. Can you link to the branch on your fork with your changes?

**Comment by AlainODea** [comment]
@mraible #116 was merged and addresses this. This can be closed.
