### ISSUE TITLE
OKTA_AWS_ROLE_TO_ASSUME does not work

### ISSUE THREAD

**Issue by hao-public** [oktadeveloper/okta-aws-cli-assume-role#119]
I cannot get the OKTA_AWS_ROLE_TO_ASSUME property to work. I test with an AWS account where I have access to 2 Federated IAM Roles: Admin and Developer.

I add the following line to the config.properties file:
OKTA_AWS_ROLE_TO_ASSUME=Admin

However, the tool still presents me with the choice of selecting either the Admin or Developer role from from the command line.

**Comment by smashling** [comment]
The way it works in the latest version, is after you select the role from the list, it remembers your profile and role. This way, you never need to select from the role list again after the initial setup. the command structure in the command line in the latest version is: aws profilename command. I reccomend updating to the latest jar if you have not yet.

**Comment by hao-public** [comment]
Thank you.
