### ISSUE TITLE
Classpath property

### ISSUE THREAD

**Issue by loopingz** [oktadeveloper/okta-aws-cli-assume-role#124]
I did an update in the past to be able to load the config.properties from the classpath.
It has been removed with recent modification.

Why loading from the classpath, this way you distribute to your team a simple jar that is already configured for your environment, and the packaging is simple:
```
zip okta.jar config.properties
```

Should I start using a fork or will you consider adding it back?

As a side note, I'm at Oktane

**Comment by AlainODea** [comment]
You're right. 

It looks like support for config.properties on the classpath was lost. Sorry about that.

It could be restored here as a fallback for absent configuration:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/src/main/java/com/okta/tools/OktaAwsConfig.java#L19-L25

```java
Optional<Path> configOptional = getConfigFile();
if (configOptional.isPresent()) {
    Path configFile  = configOptional.get();
    try (InputStream config = new FileInputStream(configFile.toFile())) {
        properties.load(new InputStreamReader(config));
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
} else {
    try (InputStream config = OktaAwsConfig.getResourceAsStream("config.properties")) {
        properties.load(new InputStreamReader(config));
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
}
```

I would support that functionality being restored.

**Comment by loopingz** [comment]
Thanks @AlainODea 

Yes, you got the idea, do you want me to PR? You already did everything so the credit should go to you.

**Comment by AlainODea** [comment]
Please. Sorry, I meant to get back to you earlier.

**Comment by AlainODea** [comment]
I'd prefer to promote contributors like yourself rather than taking credit. I've just napkin-sketched an idea with no testing so I shouldn't be credited for it.

This project will really thrive with a few folks like you actively looking at it.

**Comment by loopingz** [comment]
@AlainODea ok, I'm travelling in the next weeks, but will try to contribute it back in the next days

**Comment by AlainODea** [comment]
@loopingz any luck with this?

**Comment by loopingz** [comment]
Sorry got lost in vacation, I'll get back to you

**Comment by AlainODea** [comment]
No worries at all, @loopingz. Thank you for taking this on.

**Comment by loopingz** [comment]
I finally got some time to do the PR, sorry for the delay.
Does some of you are going to Blackhat / Defcon this year? It would be nice to meet
