### ISSUE TITLE
[Feature request] OKTA_{PASSWORD_CMD,MFA_CHOICE}

### ISSUE THREAD

**Issue by pbrisbin** [oktadeveloper/okta-aws-cli-assume-role#128]
Hi there-

Thanks a ton for this great tool, it's making it super smooth for us to include AWS API access with our "everything via Okta" initiative. I would like to request two variables be added to `config.properties` support:

- `OKTA_PASSWORD_CMD=<shell command>`

  If present, this command will be invoked to get the password

  This can be use to read from `pass(1)`, 1Password CLI, netrc, whatever. This is common in tools like ssh-add, msmtp, or isync/mbsync.

  Ideally this would get passed to `sh -c`, so I can set it to `"pass <argument>"`, but it would also be OK if it needed to be just the name of an executable because of security concerns with sending user input to a shell (I would just have to write a special-purpose wrapper).

- `OKTA_MFA_CHOICE=1|2`

  If present, skip the prompt about which MFA style to use

Variable names are totally up for bike-shedding.

**Comment by AlainODea** [comment]
I like this idea, @pbrisbin !

This is neat.

Give that this tool already shells out to random things passed in argv, I think allowing arbitrary commands in OKTA_PASSWORD_CMD is an acceptable added risk :)

The naming you suggest seems reasonable.

For OKTA_MFA_CHOICE, I'm not sure numbers will work. The order of the factors changes depending on recent factor usage. It might be better to set a type like `OKTA|RSA|SYMANTEC|GOOGLE|DUO|YUBICO`

Take a glance at the Factors API and see what you think a good lookup string could be:
https://developer.okta.com/docs/api/resources/factors#list-enrolled-factors
https://developer.okta.com/docs/api/resources/factors#factor-type

**Comment by pbrisbin** [comment]
To complete the operation, do you need to know only the _Provider Type_ also the _Factor Type_?

I agree the _Provider Type_ values make sense, so the you gave there seems great to me. If you need to be given both provider and factor type, then maybe `{Provider}.{FactorType}` might be good, e.g. `OKTA.push`

**Comment by AlainODea** [comment]
Good point. It's the factor type, not the provider type.

https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/810d19b0d116bb11a5bafbab647db9d7d0be5bd0/src/main/java/com/okta/tools/authentication/OktaMFA.java#L32-L61

**Comment by AlainODea** [comment]
@pbrisbin I'm attempting to implement OKTA_PASSWORD_CMD now. Do you anticipate having to interact at the shell with the command that is run?

**Comment by AlainODea** [comment]
I've got this working with macOS Keychain using the **security** command 🎉  I'll have a PR with the initial version of this shortly.

**Comment by AlainODea** [comment]
I've added OKTA_PASSWORD_CMD support to #184. https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/184/commits/4d1e4561e8131ecd91f7857fa9644aff850d33a1

**Comment by pbrisbin** [comment]
Much excite :tada: 

> Do you anticipate having to interact at the shell with the command that is run?

I don't personally need that because I use `pass(1)` which will just give the password without interaction as long as my GPG key has been unlocked in the running agent (and it always is). But I can't speak for other use-cases.

**Comment by AlainODea** [comment]
@pbrisbin thank you. The current implementation is not shell interactive. That’s probably fine for most tools like **pass** and **security**.

**Comment by AlainODea** [comment]
I'm going to close this. If the remaining features are still desired, please open separate issues for them.
