### ISSUE TITLE
Extending CLI session duration & Okta+awscli setup documentation

### ISSUE THREAD

**Issue by tchilcutt** [oktadeveloper/okta-aws-cli-assume-role#137]
Hello, I recently had an Okta support case (# 00465201) open for this, but after a little back and forth the case owner advised that I instead open a Github issue ticket for the dev team to address.

My initial inquiry is about extending the duration of CLI sessions.  I know there have been other questions about this, but earlier this year AWS introduced the ability to extend the CLI session for federated logins up to 12 hours (from the default of 1).  Per the case and as a test, I tried adding the OKTA_STS_SESSION parameter to my config.properties file (as described here https://github.com/oktadeveloper/okta-aws-cli-assume-role#configuring-the-application), but my federated CLI sessions continue to timeout after 1 hour.

I then got to thinking that perhaps my version of the okta-cli tool is out of date, as I originally setup our Okta+AWS integration back in 2016.   I noticed there is a new(er) version of the okta-aws-cli jar file (https://github.com/oktadeveloper/okta-aws-cli-assume-role/releases), so then thought mabye I needed to download that and/or the entire repo and start from scratch. Unfortunately, downloading just the new jar file (okta-aws-cli-1.0.2.jar) or the entire repo is not helping. I keep running into "request has expired" errors or java issues.

Additionally, the instructions on both the Github code page and the Okta support page (https://support.okta.com/help/Documentation/Knowledge_Article/Integrating-the-Amazon-Web-Services-Command-Line-Interface-Using-Okta) appear to not be correct/entirely up-to-date. In some spots they are a little vague, they seem to be missing steps for use on Windows machines, and not fully updated. For example, the latest jar file to download is named okta-aws-cli-1.0.2.jar, but everywhere in the setup/installation steps the instructions talk about the old file name (oktaawscli.jar). The instructions do not say if we are supposed to rename the file, etc. The Github instructions also mention a lib folder, as well as needing the AWS Java SDK, but the current repo does not contain a lib folder. The old installation (aka what I've been using for almost 2 years) does. 

If I download the entire repo and try to start from scratch, I am not completely sure which files in the repo are absolutely needed and which I can perhaps dispose of. When I originally setup the AWS-Okta-cli integration 2 years ago, I was advised I only needed a lib and out directory and the files therein.

Thank you.

Tom

**Comment by tchilcutt** [comment]
Hello, I am still looking for some assistance here.  Thank you.

**Comment by AlainODea** [comment]
Not sure why no one from Okta acted on this. I'm converting a couple of install scripts I have and will contribute those soon. Windows, macOS, and Linux should work with these scripts.

**Comment by AlainODea** [comment]
This is related to #88 and #93.

**Comment by AlainODea** [comment]
@tchilcutt I have installers for Windows and macOS/Linux coming in #146. They can be used today with minor tweaks.

Note: to set expecations: I don't work for Okta. I'm an Okta customer. I am not paid to work on this and do it mostly on my personal time.

**Comment by tchilcutt** [comment]
Hello @AlainODea thank you very much for your replies and for providing your installers.  I appreciate it.  Unfortunately, I have been too busy to give them a try, and I am now leaving on holiday, but I will certainly give them a spin upon my return.

And yes, it is quite unfortunate that I have still not received any response from Okta support.  Hopefully I will one day.

**Comment by AlainODea** [comment]
@tchilcutt thank you for your kind words and support. It’s my pleasure. I’m glad when these things work out.

Okta is still finding it’s feet with developer advocacy. The acquisition of StormPath was a good move and once the folks get past the huge hurdle of building the initial sustainable SDKs and frameworks, I think we’ll see a major uptick in developer support engagement.

**Comment by AlainODea** [comment]
@tchilcutt any luck with the updated readme and installers?

**Comment by tchilcutt** [comment]
Hello @AlainODea, I just returned from holiday last night.  I have quite a bit of catching up to do but I will let you know when I get around to testing your fix.  Much appreciated.

**Comment by AlainODea** [comment]
@tchilcutt my pleasure. If you run into any issues, let me know and I'll do my best to address them. We make really heavy use of this tool now where I work, so having folks identify all the rough edges really helps me and my colleagues too.

**Comment by AlainODea** [comment]
@tchilcutt the STS duration is likely broken by writing ~/.aws/config. I've pushed up #211 to stop altering that file which should mean AWS CLI uses the role assumed from Okta directly rather than trying to assume that role itself and overwriting the OKTA_STS_DURATION you set with a 3600 second (1 hour) default. It's waiting on code review.
