### ISSUE TITLE
Configurations with nested configs improperly handeled

### ISSUE THREAD

**Issue by frosforever** [oktadeveloper/okta-aws-cli-assume-role#141]
Existing `~/.aws/config` with nested properties are overwritten improperly by this tool.
For example, `s3` configuration uses [indentation for its properties](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html) e.g.
```
[profile development]
aws_access_key_id=foo
aws_secret_access_key=bar
s3 =
  max_concurrent_requests = 20
  max_queue_size = 10000
```
When `awscli` is run, the `config` is written out like so:
```
[profile development]
aws_access_key_id=foo
aws_secret_access_key=bar
s3 =
max_concurrent_requests = 20
max_queue_size = 10000
```
which is not correctly read by `aws s3` commands!

Specifically, the following test https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/054c45c5b0b58195db45bd25b528c0436331d7ed/src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java#L110-L130 if modified to contain s3 keys as follows:
```java
    @Test
    void addOrUpdateProfileToExistingProfile() throws IOException {
        final String existingCombined = manualRole + "\n"
                + "s3 =\n"
                + "    max_queue_size = 1000" + "\n\n" + existingProfile;

        final StringReader configurationReader = new StringReader(existingCombined);
        final StringWriter configurationWriter = new StringWriter();
        final Configuration configuration = new Configuration(configurationReader);

        final String updatedPrefix = "updated_";
        final String expected = "[profile " + profileName + "]\n"
                + Configuration.ROLE_ARN + " = " + updatedPrefix + role_arn + "\n"
                + SOURCE_PROFILE + " = " + profileName + "_source\n"
                + Configuration.REGION + " = " + region + "\n"
                + "s3 =\n"
                + "    max_queue_size = 1000"
                + "\n\n" + existingProfile;


        configuration.addOrUpdateProfile(profileName, updatedPrefix + role_arn);
        configuration.save(configurationWriter);

        String given = StringUtils.remove(configurationWriter.toString().trim(), '\r');

        assertEquals(expected, given);
    }
```
will not pass.

**Comment by AlainODea** [comment]
This is definitely a bug and very annoying for us as well. Sorry about this.

I think Ini4j doesn't handle nested properties. I think the AWS SDK writes the config directly without using an Ini file format library. We might have to do the same thing here.

**Comment by AlainODea** [comment]
@frosforever I have a working fix. It just needs a code review. Do you have Java experience or know someone who does who can give this a once over?
