### ISSUE TITLE
OKTA_BROWSER_AUTH not really working 

### ISSUE THREAD

**Issue by ghnboy** [oktadeveloper/okta-aws-cli-assume-role#142]
I have OKTA_BROWSER_AUTH=true set in the config file, but instead of taking me back to the commandline prompt after authenticating with Okta, it will log me into AWS Console via the Java browser. I also got an Java error on the terminal
![image](https://user-images.githubusercontent.com/41447765/42979121-a289a0d8-8b9e-11e8-84ec-58756a32df76.png)

**Comment by AlainODea** [comment]
Duplicate of #120. Fixed by #130 which has been merged but not released.

@ghnboy can you close this and follow #120 instead?

**Comment by ghnboy** [comment]
Closing this issue now, duplicated with #120
