### ISSUE TITLE
Disable Re-Login Attempts

### ISSUE THREAD

**Issue by atifrasheed79** [oktadeveloper/okta-aws-cli-assume-role#144]
There is no documented option to disable auto login attempts in case of invalid username and password. Now if it happens by mistake you get your account locked in matter of seconds. awscli shouldn't reattempt by default as standard identity policies these days lock account on consecutive 3 invalid attempts. 

It should be disabled by default and give an option to enable auto re-attempts, or should give an option to disable login re-attempts if enabled by default.

**Comment by AlainODea** [comment]
@atifrasheed79 good catch. Re-attempting with a saved password is guaranteed to fail. The cleverness of trying to handle interactive and stored config is biting back 😄 

I'll take a look at this. Should be a quick fix.

**Comment by atifrasheed79** [comment]
Thanks for your quick action @AlainODea :) Appreciate it.
