### ISSUE TITLE
OKTA_CREDENTIALS_SUFFIX ignored when writing AWS configuration

### ISSUE THREAD

**Issue by jimlawton** [oktadeveloper/okta-aws-cli-assume-role#164]
The fix for #161 still unconditionally uses `_source` in the AWS configuration file. 
It should honor the environment setting `OKTA_CREDENTIALS_SUFFIX` (or its default value if not set) instead of always using `_source`.

**Comment by AlainODea** [comment]
Good catch. My test "worked" only because I had the _source named credentials profile from before.

I like your fix. Can you open a PR with it?

**Comment by jimlawton** [comment]
#164
