### ISSUE TITLE
Unable to generate key pair

### ISSUE THREAD

**Issue by shankerm-ti** [oktadeveloper/okta-aws-cli-assume-role#170]
Hello,

I am using latest release and it was working for me 20 days ago. I tried today and it stopped working.

======================================
mshanker-mbp-13:.okta mshanker$ java -jar okta-aws-cli-1.0.2.jar
Username: mshanker@myoktaorg.com
Password:

Multi-Factor authentication is required. Please select a factor to use.
Factors:
[ 1 ] : Okta Verify (Push)
[ 2 ] : Okta Verify (TOTP)
Selection: 1

Push Factor Authentication
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
Aug 08, 2018 11:21:16 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: Okta_Verify_Autopush_1039367086=false;Version=1;Path=/;Max-Age=31536000;Secure;Expires=Thu, 08 Aug 2019 05:51:16 GMT;HttpOnly". Invalid 'expires' attribute: Thu, 08 Aug 2019 05:51:16 GMT
Waiting for you to approve the Okta push notification on your device...
201118c-aOM0MMMLyvzzMYQlLEn9QXJEmouwh-mbsg1SmdyVxx9XXRb
Exception in thread "main" java.lang.RuntimeException: You do not have access to AWS through Okta.
Please contact your administrator.
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAws(OktaSaml.java:53)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:45)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:88)
	at com.okta.tools.awscli.main(awscli.java:33)
mshanker-mbp-13:.okta mshanker$
mshanker-mbp-13:.okta mshanker$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
mshanker-mbp-13:.okta mshanker$
mshanker-mbp-13:.okta mshanker$ uname -a
Darwin mshanker-mbp-13 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
mshanker-mbp-13:.okta mshanker$

======================================

Although it says "You do not have access to AWS through Okta.", I am able to login through browser and AWS app shows in my Okta.

Thanks,
Malyaj Shanker

**Comment by AlainODea** [comment]
It looks like a problem with the support for Okta Push. I haven’t tried Okta Push myself.

Do you get the push notification in the Okta Verify app on your phone?

**Comment by shankerm-ti** [comment]
Yes and I did approve it.

In fact, I tried a few other open source tools to generate keys through okta and found that they have stopped working too. Push and TOTP both are not working.

===================
mshanker-mbp-13:.okta mshanker$ java -jar okta-aws-cli-1.0.2.jar
Username: mshanker@myoktaorg.com
Password:

Multi-Factor authentication is required. Please select a factor to use.
Factors:
[ 1 ] : Okta Verify (Push)
[ 2 ] : Okta Verify (TOTP)
Selection: 2

OKTA Token Factor Authentication
Enter 'change factor' to use a different factor
Token:
205638
Exception in thread "main" java.lang.RuntimeException: You do not have access to AWS through Okta.
Please contact your administrator.
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAws(OktaSaml.java:53)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:45)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:88)
	at com.okta.tools.awscli.main(awscli.java:33)
mshanker-mbp-13:.okta mshanker$

===================

I wrote a script myself (based on https://aws.amazon.com/blogs/security/how-to-implement-a-general-solution-for-federated-apicli-access-using-saml-2-0/) and found that the authentication is successful (I am doing it through Okta API). 
The problem is when the script tries to access Okta AWS URL after successful authentication (e.g. https://MYORG.okta.com/home/amazon_aws/1a2b3c4d5e6f7g8h9i/111) . It redirects to login page which doesn't recognise the browser and doesn't redirect further to https://signin.aws.amazon.com/saml to get the "SAMLResponse".

I think that some change on the Okta end caused this. May be it requires some cookie to be set or something else.

**Comment by AlainODea** [comment]
@shankerm-ti do you think you could adapt your script to Java and integrate it with this project and submit a PR?

**Comment by AlainODea** [comment]
@shankerm-ti I just opened #173 which should help differentiate between the different failure modes here.

I just tested Okta Verify using token (TOTP-style) with an org-level authentication sign-on policy requiring MFA and it worked.

If you have prompt for re-authentication turned on in an App Sign On Rule, that also currently isn't supported.

I'm not sure how to test Okta Push as I have it enabled and it doesn't appear to be working.

**Comment by shankerm-ti** [comment]
@AlainODea I am sorry, I won't be able to convert it to Java. I used the same python script given in the link and changed the part for authentication to use API. Rest was same.

I re-looked at my Okta configuration and found that my Okta Super Admin has enforced app level MFA on all apps. I disabled that for AWS and it started working. 

Apologies for the false alarm.

Thanks,
Malyaj Shanker

**Comment by AlainODea** [comment]
No need to apologise, @shankerm-ti!

What you experienced is a bug with MFA errors that #172 fixes. It would have made this fail right away with a clear message.

I have some better error messaging coming in #173 that indicates the kind of policy that is unsupported.

I’m glad this is working again for you.
