### ISSUE TITLE
Ability to store password in clear text

### ISSUE THREAD

**Issue by loopingz** [oktadeveloper/okta-aws-cli-assume-role#171]
I discovered that we can now store password with OKTA_PASSWORD variable.

I think this defeat the all purpose of using okta-aws for security reason, with that we expose an SSO password which leads to probably other systems.

I don't think the client should handle that.

What are your opinions?

**Comment by AlainODea** [comment]
Removing it is tricky as people may depend on it. I agree that using it defeats the purpose of the tool.

This is a hard one. Perhaps a strongly-worded security caution in the readme and/or a stderr log warning.

**Comment by mmaha** [comment]
Perhaps an approach such as https://github.com/99designs/aws-vault to store
creds in the native OS keychain store?

**Comment by AlainODea** [comment]
@mmaha that’s a good idea. #128 talks about having a password command or process and #59 talks about being a process of that kind for boto3 and AWS CLI clients.

I think it is a good idea.

aws-vault solves a different, but very significant problem of leaking AWS credentials (even temporary ones like this tool generates) in plaintext to disk.

I think it would be interesting to see how this tool could be integrated with aws-vault. Its approach appears to be quite clever and universal.
