### ISSUE TITLE
Wrong command in readme . aws sts get-caller-identity

### ISSUE THREAD

**Issue by Thinkerinhell** [oktadeveloper/okta-aws-cli-assume-role#174]
In the readme.md, Usage section,  the command shall be 
aws sts get-caller-identity

**Comment by AlainODea** [comment]
The usage section expects that you’ve used the installer (install.sh or Install-OktaAwsCli.ps1).

It makes an alias called aws whose first argument is the profile name.

`aws test sts get-caller-identity` calls WithOkta with a profile name of **test** and a command of `aws —profile test sts get-caller-identity`.
