### ISSUE TITLE
CentOS 7 Install script fails.

### ISSUE THREAD

**Issue by thatrevguy** [oktadeveloper/okta-aws-cli-assume-role#175]
When following the installation instructions the install shell script fails here due to insufficient priveleges:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/bin/install.sh#L80-L86

Should this command be run with `sudo`?

**Comment by AlainODea** [comment]
Good catch. It was written with macOS and Homebrew in mind. The install script should probably have an overridable $PREFIX which defaults to /usr/local/bin/ on macOS.

Running it with sudo should fix the issue you encountered. You could also create ~/bin/, add it to your PATH, change the path in install.sh to ~/bin/withokta and rerun it.
