### ISSUE TITLE
Add option to export EnvVars

### ISSUE THREAD

**Issue by thatrevguy** [oktadeveloper/okta-aws-cli-assume-role#177]
It'd be handy if there's an option to export "AWS_ACCESS_KEY_ID, AWS_SECRET_KEY, AWS_SESSION_TOKEN" as EnvVars in lieu of writing to the AWS profiles file.

Use case would be for any tools that can load auth from those EnvVars.

**Comment by AlainODea** [comment]
@thatrevguy this is a very good idea. Most downstream tools and SDKs recognize those env vars. It also makes the sessions inherently one-off and transient.
