### ISSUE TITLE
okta-aws-cli-assume-role for .Net

### ISSUE THREAD

**Issue by alex-valchuk** [oktadeveloper/okta-aws-cli-assume-role#186]
Hi,

I'm working on a .net port of okta-aws-cli-assume-role for my personal needs, and think it might be useful for other people.

https://github.com/alex-valchuk/okta-aws-cli-assume-role.net

**Comment by AlainODea** [comment]
@alex-valchuk cool. If you have questions, I’m happy to field them as time permits.

**Comment by AlainODea** [comment]
Since this is an informational issue and not really a bug or feature request, I'm going to close it and keep the conversation open for discussion purposes if needed.
