### ISSUE TITLE
Docker image available - add to readme eventually?

### ISSUE THREAD

**Issue by tom-smith-okta** [oktadeveloper/okta-aws-cli-assume-role#188]
**Is your feature request related to a problem? Please describe.**
This is not really a feature request, but a notification that I have built a docker image that makes installing and using this tool easier (IMHO). I'm suggesting that it be added to the readme, but I would like a few more people to test it.

The docker image is here:
https://hub.docker.com/r/tomsmithokta/okta-awscli-java/

The github repo (Dockerfile) is here:
https://github.com/tom-smith-okta/okta-awscli-java

**Comment by AlainODea** [comment]
@tom-smith-okta can you update the Docker image to use the main repo's install.sh? My #189 fix should make that practical now. I've got the readme changes drafted.

**Comment by AlainODea** [comment]
My tests work with this Docker image using console auth and a TOTP factor. Neat solution.

Note: It does not work with OKTA_BROWSER_AUTH for me. This is not surprising as it requires JavaFX and a graphical console. I suspect it could work with some incredible X11-forwarding gymnastics.
