### ISSUE TITLE
OKTA_BROWSER_AUTH doesn't work with multiple roles

### ISSUE THREAD

**Issue by robkinyon-roivant** [oktadeveloper/okta-aws-cli-assume-role#191]
**Describe the bug**
I have two AWS accounts - one where I have one role I can assume and one where I have multiple roles I can assume. Using `OKTA_BROWSER_AUTH=true`, I get prompted for my credentials, then the following happens:

- In the account with one role, i get the one role, my credentials get written to ~/.aws/credentials, and life is good.
- In the account with multiple roles, I go to a second screen which prompts me to pick my role. I select a role and then end up in AWS **in the browser**. I quit the browser and nothing is written to ~/.aws/credentials.

**Additional context**
If, instead, I set `OKTA_BROWSER_AUTH=false`, I provide my password as I always have, then get a prompt in the commandline to select my role, and life is good.

**Comment by AlainODea** [comment]
@robkinyon-roivant I tried this with a single account and multiple roles and multiple accounts with multiple roles and was not able to reproduce it. In both cases I had a single Okta org with a single Amazon Web Services app set up with multiple AWS accounts.

That the embedded browser is proceeding to the AWS SAML sign-on page graphically suggests that the SAMLResponse can’t be found in the web page returned by the Amazon Web Services Okta app.

That web page should have a form with the SAMLResponse, RelayState, and JavaScript to automatically POST it to AWS’ SAML sign-on page.

The code is meant to intercept the web page document before the WebView renders it. It looks for the SAMLResponse and, if it finds it, it closes the WebView and proceeds with the console role selection flow.

Are you using the v1.0.3 release? There are some serious bugs with browser auth in v1.0.2.

**Comment by robkinyon-roivant** [comment]
Upgrading fixed the problem. Thanks!
