### ISSUE TITLE
OKTA_BROWSER_AUTH doesn't respect IWA login

### ISSUE THREAD

**Issue by robkinyon-roivant** [oktadeveloper/okta-aws-cli-assume-role#192]
**Describe the bug**
If I login to Okta with Chrome or IE, IWA triggers and uses my AD credentials on my laptop to authenticate with Okta. I don't have to type my username or password.

If I do that via the CLI tool, the browser says it's logging in with IWA, then asks me for my credentials.

**Expected behavior**
I expect all browsers launched on my laptop to behave the same way, regardless of how it was launched.

**Comment by AlainODea** [comment]
@robkinyon-roivant I think this is a limitation of JavaFX WebView. It also doesn't support FIDO U2F, which is frustrating. Sorry about this.

I've looked into using Chrome directly instead of an embedded, but I haven't figured it out.

**Comment by mh-psaad** [comment]
Weird, this works fine for us. It didn't with an earlier build from July/August timeframe, but it works now. Can you delete your .okta and .aws folders and start from scratch using the latest version?

![image](https://user-images.githubusercontent.com/43017097/47183190-31815e00-d2dc-11e8-9363-5a678df1af22.png)

![image](https://user-images.githubusercontent.com/43017097/47183057-e7987800-d2db-11e8-89c4-2a20efa4cbc6.png)

**Comment by AlainODea** [comment]
@mh-psaad this is good to know. I wonder if this is because of the switch to OpenJFX in v1.0.5 from whatever is included with Java 8.

@robkinyon-roivant can you try IWA on v1.0.5 and see if this is now resolved?

**Comment by AlainODea** [comment]
@mh-psaad thank you for investigating this and providing such clear analysis and screenshots here. I really appreciate it.

**Comment by AlainODea** [comment]
This is fixed by a later JRE in all likelihood.

**Comment by duhaas2015** [comment]
@robkinyon-roivant I'm curious if you still experience this issue?  we are currently looking to roll out the latest version that supports browser auth and for the most part, things are working well.  one of the outstanding issues we continue to see if our need to fill in username/password vs. IWA passing me through.  @AlainODea curious if you had learned of the actual fix for this issue?

**Comment by robkinyon-roivant** [comment]
@duhaas2015 We've migrated away from running this on Windows, so we have no way of replicating. We're very happy with how 1.0.6 is behaving on Centos, even without IWA. It remembers my username, sends the push automatically, etc.

**Comment by duhaas2015** [comment]
Thats cheating @robkinyon-roivant  :)  Thanks for following up, let me know if i'm missing something or you have other feedback @AlainODea

**Comment by duhaas2015** [comment]
> Weird, this works fine for us. It used to not work with an latest build that was available on August 23rd, which is when I started using this tool, but it works now. Can you delete your .okta and .aws folders and start from scratch using the latest version?
> 
> ![image](https://user-images.githubusercontent.com/43017097/47183190-31815e00-d2dc-11e8-9363-5a678df1af22.png)
> 
> ![image](https://user-images.githubusercontent.com/43017097/47183057-e7987800-d2db-11e8-89c4-2a20efa4cbc6.png)

what version of Java were or are you using?

**Comment by duhaas2015** [comment]
We believe we’ve narrowed it down to version 181 of the jdk works and version 202 of the jdk does not when running jdk8.  Still trying to understand what the suttle difference is thats causing the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SwatiWaghmare2022** [comment]
![Untitled](https://user-images.githubusercontent.com/98100385/151774712-53ad2b7c-c224-4a06-abcf-37eca4a41d64.png)

Hello,

I am getting the same error as mentioned above. JavaFx browser is stopped at this windows and doesn't proceed with the rest of the authentication. Any suggestion to make this work. Please let me know. Currently I have below JAVA version at my end.

java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
