### ISSUE TITLE
Configurable credentials file path

### ISSUE THREAD

**Issue by alex-valchuk** [oktadeveloper/okta-aws-cli-assume-role#193]
It would be nice to have a possibility to configure an output path for a credentials file instead of writing it
to the default "user.home/.aws" directory.

Currently I have to add an additional command that copies the credentials file to my working folder.

**Comment by AlainODea** [comment]
@alex-valchuk I’m open to this, but I want to understand it better.

Is OKTA_ENV_MODE a solution for your case?

How do your downstream scripts or code use the alternate AWS credentials location?

**Comment by alex-valchuk** [comment]
1. OKTA_ENV_MODE does not fit.
We already use  AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN as environment vars.

It's much more safer to work with profiles. 

2. In my ASP.NET application I need to use something specific as a path to credentials file (e.g. c:\aws\credentials) because the config is common for our team of developers and somebody from them could just trivially store it's user profile in a location that differs from default c:\Users\%username%.
Additionally application that is run under IIS does not see the default credentials file.

3. It would be also nice to be able to install the tool in any location. Not only in Home.User\.okta

**Comment by AlainODea** [comment]
1. **OKTA_ENV_MODE** sets sub-process environment only. Persistent user and system environment are not modified. It is safe to use alongside other programs that depend on the persistent environment.

2. This tool was designed for interactive use, not for services or systems use. Using this within IIS would definitely be tricky.  Would implementing https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/59 work?

3. The binary installation path can be changed. It's controlled by the **-classpath** switch on **java** in the **With-Okta** Cmdlet (assuming you are using the PowerShell installer):
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/0c90ad69f65415652455072305f187b9d398f10f/bin/Install-OktaAwsCli.ps1#L65

     If config.properties is in the current working directory, then it will take precedence over the one in ~/.okta/config.properties.

**Comment by AlainODea** [comment]
@alex-valchuk you can control the parent of the .okta directory by passing **-Duser.home** to **java** in that same location in the installer.

One possibility would be changing that line to the following:
```powershell
java "-Duser.home=C:\" "-Dhttp.proxyHost=$ProxyHost" "-Dhttp.proxyPort=$ProxyPort" "-Dhttps.proxyHost=$ProxyHost" "-Dhttps.proxyPort=$ProxyPort" "-Dhttp.nonProxyHosts=$NonProxyHosts" -classpath $HOME\.okta\* com.okta.tools.WithOkta @args
```

The tool will then expect C:\.okta\config.properties, store cookies to C:\.okta\cookies.properties, store AWS config to C:\.aws\config, and store AWS credentials to C:\.aws\credentials.

Would that server your need?

**Comment by AlainODea** [comment]
Closing this for now as there is a workaround using JVM system properties.
