### ISSUE TITLE
`updateConfigFile` unable to read existing aws config

### ISSUE THREAD

**Issue by frosforever** [oktadeveloper/okta-aws-cli-assume-role#197]
**Describe the bug**
`updateConfigFile` in `ConfigHelper` https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/87f90ac171ae3888d6681bc2b5c0781433353a34/src/main/java/com/okta/tools/helpers/ConfigHelper.java#L21 is unable to read existing AWS configs.
The root bug apears to be in `usingPath` in `FileHelper` https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/87f90ac171ae3888d6681bc2b5c0781433353a34/src/main/java/com/okta/tools/helpers/FileHelper.java#L113 that opens both a `Reader` and `Writer` to the same file. However, creating a new `FileWriter` https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/87f90ac171ae3888d6681bc2b5c0781433353a34/src/main/java/com/okta/tools/helpers/FileHelper.java#L90 on an existing file will truncate the file unless `append = true`.

**To Reproduce**
The following main method will read nothing even if something is present in the file. It assumes the file exists, has content, and that the `FileHelper` methods are accessible.
```java
    public static void main(String[] args) throws Exception {
        Path awsConfigPath = FileHelper.getAwsDirectory().resolve("config");
        System.out.println("AWS config Read using readAllLines:");
        List<String> allLines = Files.readAllLines(awsConfigPath);
        allLines.forEach(System.out::println); //This will print the existing files contents

        System.out.println("Reading using FileHelper.usingPath ...");
        FileHelper.usingPath(awsConfigPath, (reader, writer) -> {
            //This will print nothing as the file has already been truncated after a writer was opened
            new BufferedReader(reader).lines().forEach(System.out::println); 
        });

        //Write the content back out so it doesn't empty the file each time
        Files.write(awsConfigPath, allLines);
    }
```

**Comment by AlainODea** [comment]
Really good catch here, @frosforever. I knew there was something I was missing when having a reader and writer on the same file. Not sure why I missed this bug. I’m glad you found it.
