### ISSUE TITLE
Usage docs

### ISSUE THREAD

**Issue by jeugene** [oktadeveloper/okta-aws-cli-assume-role#198]
**Describe the bug**
https://github.com/oktadeveloper/okta-aws-cli-assume-role#usage
The docs mention to call below.  Is this a typo?
"aws test sts get-caller-identity"

Why is above calling "aws" vs "awscli" or is this code adding any hook into "aws" cli?
Is there any specific purpose to appending aws cli  "sts get-caller-identity"

**Expected behavior**
Is the expected usage "awscli --profile tester" // this sets up profile for aws cli. Then execute any aws cli specific commands?

**Comment by AlainODea** [comment]
It's not a typo.

**aws** is a shell function created by install.sh or Install-OktaAwsCli.ps1. The **awscli** script in bin is a legacy thing.
