### ISSUE TITLE
Does MFA in this app work with current versions of Okta?

### ISSUE THREAD

**Issue by khourybrazil** [oktadeveloper/okta-aws-cli-assume-role#2]
The article published [here](https://support.okta.com/help/articles/Knowledge_Article/Integrating-the-Amazon-Web-Services-Command-Line-Interface-Using-Okta) seems to indicate that MFA works but that doesn't seem to be the case in my testing. I get this result every time I try to use it with MFA required in my sign on policy:

`You do not have access to AWS through Okta.
Please contact your administrator.`

When I test access through the browser I get prompted for MFA and it works as expected.

**Comment by khourybrazil** [comment]
I ran the request through mitmproxy and it looks like this fails when you enforce MFA at the app level. If you enforce MFA at the app level it returns status "SUCCESS" and an attempt to validate the token results in a 302 redirect to https://<company>.okta.com/policy/second-factor which ultimately fails. If you have MFA enforced at the global level it returns status "MFA_REQUIRED" as expected. I'm not sure if that's a use case you're interested in supporting so if not feel free to close this.

**Comment by raphaellondner-okta** [comment]
What you find is correct: we only support MFA at the organization level, not the app level. That is because we (sadly) don't yet support app-level sign-on policy in our public Policies API. We'd obviously love to support this scenario as well, but have to wait until app policies are exposed through our public API. I have forwarded your comments to product management and also updated this Readme file to clearly mention we only currently support organization-level MFA policies.

**Comment by johnsmyth** [comment]
I realize that this issue was closed due to lack of api support - Has this been implemented in the public API yet?  We need this capability in our organization.

**Comment by etendards** [comment]
We would also like to use App level MFA.  Has this project enabled that yet?

**Comment by holed03** [comment]
We have created the following workaroud for (not being able to use App level MFA to protect AWS CLI.....)

1.	In the AWS console Okta ‘app specific policy’ create a rule with exception group (checkbox) to ‘exclude following groups’ from (app specific MFA rule) [& set to your CLI users group/ DevOps]

![app specific exception rule](https://user-images.githubusercontent.com/37154643/37109885-40900f54-2233-11e8-8190-f254c1086d02.png)

2.	Combine this with Okta ‘sign-on policy’ to enforce MFA ‘assigned to groups’ [set to your CLI users group/ DevOps] ‘if users IP is anywhere’ i.e. on or off network then ‘Prompt for factor’ ‘Every time’ 

![sign-on policy rule](https://user-images.githubusercontent.com/37154643/37109914-56105334-2233-11e8-9d11-2fa643e6d175.png)

•	This will ensure AWS CLI access is protected, (along with access to all Okta app’s (by anyone in that group)
