### ISSUE TITLE
aws test doesnt work

### ISSUE THREAD

**Issue by SmoothGlide** [oktadeveloper/okta-aws-cli-assume-role#212]
Running on Windows. 
Followed the instructions to install.
When I run "aws test sts get-caller-identity" in Powershell - it cannot find aws command
When I run same in Command Prompt is just gives me the help page (aws test is not valid)

**Comment by AlainODea** [comment]
@SmoothGlide I'm in the process of removing the override of the aws command. It causes more problems than it solves.

Assuming you used the [documented install process](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/Readme.MD#installation) you can run this:
```powershell
With-Okta test aws --profile test sts get-caller-identity
```

You may want to check the content of the file pointed at by $Profile (note that notepad.exe will not read the line terminators correctly so use VSCode or another competent text editor to load it). I recommend removing the aws and sls functions. I'm removing them from the install in a PR shortly,

**Comment by AlainODea** [comment]
See #213 for the fix to remove the confusing overrides.

**Comment by SmoothGlide** [comment]
Awesome.  I got it working a little….

On Sep 28, 2018, at 11:14 AM, AlainODea <notifications@github.com<mailto:notifications@github.com>> wrote:


See #213<https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/213> for the fix to remove the confusing overrides.
