### ISSUE TITLE
Identity in the Cloudtrail entry from okta

### ISSUE THREAD

**Issue by philliphayesiam** [oktadeveloper/okta-aws-cli-assume-role#220]
**Is your feature request related to a problem? Please describe.**
When the API call is made to AWS, the cloudtrail entry ends up having the username of botocore-session-#####.  This impacts the ability to understand who has been accessing the AWS API after a call from the IdP

**Describe the solution you'd like**
Assuming this can be fixed on the dev side, we'd like the caller identity to be traced back to an individual in okta

**Describe alternatives you've considered**
Chaining together other cloudtrail events just before the API call(which are the assume role calls)
<img width="1024" alt="screen shot 2018-10-03 at 12 14 17 pm" src="https://user-images.githubusercontent.com/6117998/46423987-e83ee500-c705-11e8-9bb8-01fa118d374a.png">

**Additional context**

**Comment by AlainODea** [comment]
Does this happen with v1.0.4?

**Comment by philliphayesiam** [comment]
I see you released v1.0.4 yesterday, so, no, we installed this in early september. Hence, v.1.0.3.

**Comment by AlainODea** [comment]
No worries. This bug was just fixed, so I was really hoping it didn't come back from the grave in anticipation of Halloween :)

**Comment by philliphayesiam** [comment]
How timely.... I just installed v1.0.4 and the sts get-caller-identity looks as expected now.  Waiting for cloudtrail to catch up so I can verify on that side.  Thanks so much!

**Comment by AlainODea** [comment]
My pleasure, @philliphayesiam. I'll close this as successfully resolved :)
