### ISSUE TITLE
v1.0.4 no longer generates credentials for multiple accounts

### ISSUE THREAD

**Issue by robkinyon-roivant** [oktadeveloper/okta-aws-cli-assume-role#221]
**Describe the bug**

My Okta account has access to multiple roles across multiple AWS accounts. With v1.0.3, I could generate credentials for several accounts at the same time. When I try to do so with v1.0.4, I get credentials for the first account, but cannot generate credentials for subsequent accounts. ~/.aws/credentials only contains credentials for the first account.

**To Reproduce**
1. Install v1.04
2. Generate credentials for AWS account 1
    * You are required to login and select a role
3. See the credentials in ~/.aws/credentials
4. Generate credentials for AWS account 2
    * You not required to login (correct)
    * You are not required to select a role (INCORRECT)
5. There are no credentials for account 2 in ~/.aws/credentials
    * Either in addition to or replacing the credentials for account 1

**Expected behavior**

I can generate credentials for multiple accounts at the same time.

**Screenshots**

**Additional context**

**Comment by AlainODea** [comment]
This is frustrating. Sorry about this. I’m going to do some testing to re-validate multi-account support.

In the meantime:

> 2. Generate credentials for AWS account 1

What command do you run to do this step?

**Comment by robkinyon-roivant** [comment]
We have a script that does:

```bash
java -classpath ~/.okta/*.jar com.okta.tools.WithOkta $@
```
We then setup the ~/.okta/config.properties file with the right values (including OKTA_BROWSER_AUTH=true) invoke this script with `true` (so that it's a no-op). Our tooling is responsible for managing the config.properties file, so we rewrite it on every invocation.

We have a similar script for Windows which invokes `rundll32`, with similar results.

**Comment by AlainODea** [comment]
Thank you.

Are you setting **OKTA_PROFILE** in config.properties or the process/shell environment between switching accounts?

Setting that may alleviate this.

**Comment by robkinyon-roivant** [comment]
We specifically set:

```
OKTA_ORG=#{okta_org}
OKTA_AWS_APP_URL=#{aws_app_url}
OKTA_BROWSER_AUTH=true
OKTA_AWS_ROLE_TO_ASSUME=
OKTA_PROFILE=
OKTA_STS_DURATION=3600
```

Do we need to set the profile now as well? What should we set it to?

**Comment by AlainODea** [comment]
There are a couple of approaches you can use to solve this:
1. named profiles
2. environment mode and shells

# Solution 1: Named profiles
OKTA_PROFILE just needs to be unique per profile.

My approach is this:
1. I have an AWS account called **mycorp-mgmt** account. I call the role **mgmt**
2. I have another AWS account called **mycorp-prod** account. I call the role **prod**

This results in a credentials file like this:

```ini
[mgmt]
aws_access_key_id = <access key ID for mgmt>
aws_secret_access_key = <secret access key for mgmt>
aws_session_token = <session token for mgmt>

[prod]
aws_access_key_id = <access key ID for prod>
aws_secret_access_key = <secret access key for prod>
aws_session_token = <session token for prod>
```

Then tools like AWS CLI are used like this:

```bash
aws --profile mgmt s3 ls my-mgmt-bucket
aws --profile prod s3 ls my-prod-bucket
```

# Solution 2: Environment mode and shells

Here's something I tried that might work for you:

~/.okta/config.properties:
```properties
OKTA_ORG=acmecorp.oktapreview.com
OKTA_AWS_APP_URL=https://acmecorp.oktapreview.com/home/amazon_aws/0oa5zrwfs815KJmVF0h7/137
OKTA_BROWSER_AUTH=true
OKTA_ENV_MODE=true
```

Then I ran this in PowerShell:
```
With-Okta ignore powershell
```

I got prompted to pick a role, I picked my research account readonly role.

I then got a PowerShell session with **AWS_ACCESS_KEY_ID**, **AWS_SECRET_ACCESS_KEY**, and **AWS_SESSION_TOKEN** in the environment.

```
PS D:\Users\example.person> aws sts get-caller-identity
{
    "Account": "123456789012",
    "UserId": "AROAAABCD1234ABCD1234:example.person@example.com",
    "Arn": "arn:aws:sts::123456789012:assumed-role/ReadOnly/example.person@example.com"
}
```

This approach allows persistent shells with credentials that disappear from the user's system once the shell is closed. They'll expire according to the OKTA_STS_DURATION that you set.

You can be specific about the role they assume by setting OKTA_AWS_ROLE_TO_ASSUME to the ARN of the role you want. This would make scripts for particular accounts easier.

Example for Bash:
```bash
#!/bin/bash
export OKTA_ENV_MODE=true
export OKTA_AWS_ROLE_TO_ASSUME='arn:aws:iam::123456789012:role/ReadOnly'
java -classpath ~/.okta/*.jar com.okta.tools.WithOkta $@
```

Example for PowerShell:
```powershell
$env:OKTA_ENV_MODE = true
$env:OKTA_AWS_ROLE_TO_ASSUME = "arn:aws:iam::123456789012:role/ReadOnly"
java -classpath ~/.okta/*.jar com.okta.tools.WithOkta $@
```

You could have an unchanging ~/.okta/config.properties like this:
```properties
OKTA_ORG=#{okta_org}
OKTA_AWS_APP_URL=#{aws_app_url}
OKTA_BROWSER_AUTH=true
OKTA_STS_DURATION=3600
```

You don't need to rewrite ~/.okta/config.properties, just override it's defaults with environment variables in your scripts.

**Comment by AlainODea** [comment]
I have verified that multiple profile support is still working in v1.0.4. I'll close the issue, but continue the conversation to help work out the use case.

```bash
$ rm -Rf ~/.aws/ ~/.okta/profiles ~/.okta/.current-session ~/.okta/cookies.properties
$ okta-aws test sts get-caller-identity
# pick research read only role
{
    "Account": "123456789012",
    "UserId": "AROAAABCD1234ABCD1234:example.person@example.com",
    "Arn": "arn:aws:sts::123456789012:assumed-role/ReadOnly/example.person@example.com"
}
$ okta-aws test sts get-caller-identity
{
    "Account": "123456789012",
    "UserId": "AROAAABCD1234ABCD1234:example.person@example.com",
    "Arn": "arn:aws:sts::123456789012:assumed-role/ReadOnly/example.person@example.com"
}
$ aws --profile test sts get-caller-identity
{
    "Account": "123456789012",
    "UserId": "AROAAABCD1234ABCD1234:example.person@example.com",
    "Arn": "arn:aws:sts::123456789012:assumed-role/ReadOnly/example.person@example.com"
}
$ okta-aws test2 sts get-caller-identity
# pick research research role
{
    "Account": "123456789012",
    "UserId": "AROAAABCD1234ABCD1234:example.person@example.com",
    "Arn": "arn:aws:sts::123456789012:assumed-role/Research/example.person@example.com"
}
$ okta-aws test2 sts get-caller-identity
{
    "Account": "123456789012",
    "UserId": "AROAAABCD1234ABCD1234:example.person@example.com",
    "Arn": "arn:aws:sts::123456789012:assumed-role/Research/example.person@example.com"
}
$ aws --profile test2 sts get-caller-identity
{
    "Account": "123456789012",
    "UserId": "AROAAABCD1234ABCD1234:example.person@example.com",
    "Arn": "arn:aws:sts::123456789012:assumed-role/Research/example.person@example.com"
}
$ aws --profile test sts get-caller-identity
{
    "Account": "123456789012",
    "UserId": "AROAAABCD1234ABCD1234:example.person@example.com",
    "Arn": "arn:aws:sts::123456789012:assumed-role/ReadOnly/example.person@example.com"
}
$ okta-aws test sts get-caller-identity
{
    "Account": "123456789012",
    "UserId": "AROAAABCD1234ABCD1234:example.person@example.com",
    "Arn": "arn:aws:sts::123456789012:assumed-role/ReadOnly/example.person@example.com"
}
```

**Comment by AlainODea** [comment]
Thank you, @robkinyon-roivant. Documentation for that would definitely help and would be a very welcome contribution 👍
