### ISSUE TITLE
No clear way to assume second credentials in same account

### ISSUE THREAD

**Issue by robkinyon-roivant** [oktadeveloper/okta-aws-cli-assume-role#223]
**Describe the bug**

Given a user who has multiple roles in a given AWS account, how can I:

1. Retrieve the list of possible roles on behalf of the user so that I can do something programmatic with them?
1. Get credentials for a different role on that account while the credentials for the first role are active?

I'm presuming that if I knew which role they wanted to assume, I could set the OKTA_PROFILE to be some combination of the account name/id and the role (which is what the code does by default). This would solve #2. But, without knowing which roles are assumable by the user, I cannot set the profile name to something that would trigger the second credentials because just running `withokta` with the same profile and a blank OKTA_AWS_ROLE_TO_ASSUME results a "Yes, you have active credentials for a role in that account."

Normally, this is exactly what I want. But, I want to be able to trigger the generation of a second set of credentials if needed.

**Comment by AlainODea** [comment]
1. A new feature to output the role selection menu as JSON could support this. That is obtainable here:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/8753f9f0b2cf0281f36a89e87ef27dd1353b0205/src/main/java/com/okta/tools/helpers/RoleHelper.java#L105-L108

    Using a Jackson ObjectMapper on the return of that it's fairly easy to get JSON like this back:
    ```json
    [
        {
        "accountName": "Account: example-corp (123456789012)",
        "roleOptions": [
            {
            "roleName": "Admin",
            "roleArn": "arn:aws:iam::123456789012:role/Admin"
            }
        ]
        },
        {
        "accountName": "Account: example-research (654321234567)",
        "roleOptions": [
            {
            "roleName": "Admin",
            "roleArn": "arn:aws:iam::654321234567:role/Admin"
            }
            {
            "roleName": "ReadOnly",
            "roleArn": "arn:aws:iam::654321234567:role/ReadOnly"
            }
        ]
        }
    ]
    ```

2. My users and I do this with OKTA_PROFILE. The profile name is independent of the account and role. It's a label that means something to the user only. Once the user interactively selects the role, the relationship between the OKTA_PROFILE label and the actual AWS IAM Role ARN is written to **~/.okta/profiles**.

    **~/.okta/profiles**:
    An INI file with a section for each unique OKTA_PROFILE.
    * **source_profile**: name for the AWS profile (should match section name)
    * **okta_roleArn**: ARN of the IAM Role
    * **profile_expiry**: ISO-8601 UTC timestamp of the expiry of the STS session

    You can also do this with OKTA_ENV_MODE, but it requires setting the IAM Role ARN in OKTA_AWS_ROLE_TO_ASSUME or interacting with the role menu every time.
