### ISSUE TITLE
Creating incorrect profilenames in .aws/credentials and .okta/profiles

### ISSUE THREAD

**Issue by ohuk2** [oktadeveloper/okta-aws-cli-assume-role#225]
Hello,

looks like either the documentation or the tool is wrong, when I do for example the following I don't get a profile called "test", but called the AWS command I used :-) :

ubuntu:/.okta$ withokta test s3 ls
Username: U48xxx
Password: 
Auto select role as only one is available : arn:aws:iam::08646965xxxx:role/xxx-federated
ubuntu:/.okta$ cat profiles
[s3]
source_profile = s3
okta_roleArn = arn:aws:iam::08646965xxx:role/xxx-federated
profile_expiry = 2018-10-09T11:55:46.026551Z

ubuntu:/.okta$ cat ../.aws/credentials
[default]
aws_access_key_id = xxxx
aws_secret_access_key = xxxx

[s3]
aws_access_key_id = xxxx
aws_secret_access_key = xxxx
aws_session_token = xxxx

ubuntu:/.okta$ aws s3 --profile s3 ls
2018-07-04 01:26:18 xxxxx
2018-07-02 11:57:13 xxxxx
[...]

Am I misunderstanding the syntax?

Thanks!

**Comment by AlainODea** [comment]
@ohuk2 are you using the withokta script in bin? That won't set the OKTA_PROFILE environment. The installer scripts will give you better results.

Try running the [installer script for your platform](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/Readme.MD#installation) and then try this:

```shell
okta-aws test s3 ls
```

It should create a profile named **test** in **~/.aws/credentials** and then run `aws --profile test s3 ls`.

**Comment by ohuk2** [comment]
Thanks Alain yes I installed it as:
27  curl 'https://raw.githubusercontent.com/oktadeveloper/okta-aws-cli-assume-role/master/bin/install.sh' | sudo bash

which installed "withokta" in /usr/local/bin.

I did a "source .okta/bash_functions"  and tried as you said above and then it went OK. Might want to mention it in the doc :-) .

Thanks again :-) !
