### ISSUE TITLE
Windows: OKTA_PROFILE not respected, always have to pass --profile

### ISSUE THREAD

**Issue by mh-psaad** [oktadeveloper/okta-aws-cli-assume-role#231]
**Describe the bug**
1. Even though `OKTA_PROFILE` is set before the initial call to AWS, it doesn't seem to be used when creating the profile.
2. Further calls to `okta-aws` *always* require the profile to be passed in and `OKTA_PROFILE` is not read. Leading to weird issue when you forget to pass it in.
- Example: `okta-aws s3 ls` will create a new profile named s3 and return an error because 'ls' is not an appropriate command

**To Reproduce**
1. Run the PowerShell bootstrapper on a fresh install
2. Modify config.properties to include `OKTA_PROFILE`
3. ? What do we type to initiate the session with the default profile name we specified in #2? Or a derived one?
4. Making any call to `okta-aws` will require a profile passed in as the first parameter 

**Expected behavior**
1. It's not clear how to make the tool just use a default credential, even with just one credential created, the tool requires you to pass it in as the first argument for every single call: `okta-aws default s3 ls` works, but `okta-aws s3 ls` does not. Ironically, after you are authenticated and the cookie is set, straight up `aws s3 ls` works fine. 
2. The documentation is not clear here, and there is a hodgepodge instructions with the new way to use the tool `okta-aws` and the old way, which required a batch script in your PATH `awscli`. This should be cleaned up and any references to the old way should be removed.
3. If a profile needed to be derived, it would probably be easiest to just default to the last segment of the roleArn:
- `arn:aws:iam::160639289719:role/Test-Developer`
becomes
- `Test-Developer`

**Additional context**
I love this tool. I absolutely love it, it's just very difficult to get it set up and the settings don't work like they are described. If a PR is needed, let me know.

**Comment by AlainODea** [comment]
Thank you for reporting this.

There are definitely gaps in the docs, particularly around the renaming of commands from the previous versions.

I’ll take a deeper look at this and help get past this.

If you already have specific changes to the docs to recommend, a PR is definitely welcome :)

**Comment by AlainODea** [comment]
> 1. It's not clear how to make the tool just use a default credential, even with just one credential created, the tool requires you to pass it in as the first argument for every single call: okta-aws default s3 ls works, but okta-aws s3 ls does not. Ironically, after you are authenticated and the cookie is set, straight up aws s3 ls works fine.

You can use the default profile as follows:
```
okta-aws default s3 ls
```

`okta-aws s3 ls` won't work as it would be creating a profile named s3 and then try to run `aws --profile s3 ls` under the hood. That's why you get that error message.

It works like this:

General usage:
```
okta-aws profile-name aws-cli-subcommand
```

Example of listing all S3 buckets:
```
okta-aws test s3 ls
```

Subsequent calls to okta-aws with the same profile name should use cached AWS credentials (unless OKTA_ENV_MODE is set to true).

The first of these should prompt for Okta credentials, the others should just run:
```
okta-aws test s3 ls
okta-aws test s3 ls
okta-aws test s3 ls
```

> 2. The documentation is not clear here, and there is a hodgepodge instructions with the new way to use the tool okta-aws and the old way, which required a batch script in your PATH awscli. This should be cleaned up and any references to the old way should be removed.

I'm not sure where **awscli** usage is still documented/referenced. Can you point me to where you seeing that? I'd like to remove it.

> 3. If a profile needed to be derived, it would probably be easiest to just default to the last segment of the roleArn:
The **awscli** command will still work if you have the script. It will generate predictable profile names if you don't supply OKTA_PROFILE:
Example:
```
awscli s3 ls
```
In general, `arn:aws:iam::AccountNumber:role/RoleName` becomes `RoleName_AccountNumber`.
It will turn `arn:aws:iam::160639289719:role/Test-Developer` into `Test-Developer_160639289719`.

**Comment by mh-psaad** [comment]
> > 1. It's not clear how to make the tool just use a default credential, even with just one credential created, the tool requires you to pass it in as the first argument for every single call: okta-aws default s3 ls works, but okta-aws s3 ls does not. Ironically, after you are authenticated and the cookie is set, straight up aws s3 ls works fine.
> 
> You can use the default profile as follows:
> 
> ```
> okta-aws default s3 ls
> ```
I know how to set the default credential, but if I still have to name it for every subsequent call, it's not a default, it's just another profile. Is this just a situation where the new way of doing things (okta-aws) doesn't look at OKTA_PROFILE but the old way (awscli) did?

> > 1. The documentation is not clear here, and there is a hodgepodge instructions with the new way to use the tool okta-aws and the old way, which required a batch script in your PATH awscli. This should be cleaned up and any references to the old way should be removed.
> 
> I'm not sure where **awscli** usage is still documented/referenced. Can you point me to where you seeing that? I'd like to remove it.
> 

It's not directly referred to in the latest readme, but in the [manual install](https://github.com/oktadeveloper/okta-aws-cli-assume-role#manual-install) section of the readme, there is bit about copying the \bin folder to somewhere in your path. As far as I can tell, nothing in the bin folder is needed to make this work anymore because okta-aws and withokta are now loaded into the PowerShell or Bash profiles as user functions and don't need to be separate bat/sh scripts.

> _Copy scripts from .okta/bin to somewhere on your PATH._

> > 1. If a profile needed to be derived, it would probably be easiest to just default to the last segment of the roleArn:
> >    The **awscli** command will still work if you have the script. It will generate predictable profile names if you don't supply OKTA_PROFILE:
> >    Example:
> ```
> awscli s3 ls
> ```
> In general, `arn:aws:iam::AccountNumber:role/RoleName` becomes `RoleName_AccountNumber`.
> It will turn `arn:aws:iam::160639289719:role/Test-Developer` into `Test-Developer_160639289719`.

That's how I would expect it to work, but why doesn't aws-okta work the same way?

Maybe I am misunderstanding the entire idea of this project. Is the intended usage to use ```okta-aws profilename s3 ls``` to create the session, then use the AWS SDK directly ```aws s3 ls``` for subseqent calls. Or should all AWS CLI calls go through okta-aws?

**Comment by AlainODea** [comment]
**okta-aws** is intended to be used with an explicit profile name every time it is called. The way it is written makes it very difficult to omit the profile name from the call.

Now that I've seen more use cases, I realize that isn't the best fit for everyone. It isn't the best fit for things I do myself anymore.

I actually use a config like this in ~/.config/fish.config:
```fish
function okta-fish
    set -x OKTA_ENV_MODE true
    java -Djava.net.useSystemProxies=true  -classpath ~/.okta/okta-aws-cli.jar com.okta.tools.WithOkta "fish" $argv
end
```

For bash, this should work:
```bash
function okta-bash {
    export OKTA_ENV_MODE=true
    java -Djava.net.useSystemProxies=true -classpath ~/.okta/okta-aws-cli.jar com.okta.tools.WithOkta "bash" $@
}
```

For PowerShell, this should work:
```powershell
function Okta-New-Session {
    Write-Host $args
    $OriginalOKTA_ENV_MODE = $env:OKTA_ENV_MODE
    try {
        $env:OKTA_ENV_MODE = $True
        $InternetOptions = Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings"
        if ($InternetOptions.ProxyServer) {
            ($ProxyHost, $ProxyPort) = $InternetOptions.ProxyServer.Split(":")
        }
        if ($InternetOptions.ProxyOverride) {
            $NonProxyHosts = [System.String]::Join("|", ($InternetOptions.ProxyOverride.Replace("<local>", "").Split(";") | Where-Object {$_}))
        } else {
            $NonProxyHosts = ""
        }
        java "-Dhttp.proxyHost=$ProxyHost" "-Dhttp.proxyPort=$ProxyPort" "-Dhttps.proxyHost=$ProxyHost" "-Dhttps.proxyPort=$ProxyPort" "-Dhttp.nonProxyHosts=$NonProxyHosts" -classpath $HOME\.okta\* com.okta.tools.WithOkta powershell @args
    } finally {
        $env:OKTA_ENV_MODE = $OriginalOKTA_ENV_MODE
    }
}
```

I run `okta-fish` and it prompts me for Okta credentials (unless I have a session) and then prompts me for an AWS Role each time (unless I set **OKTA_AWS_ROLE_TO_ASSUME**)
It lets me bring up a fish shell with temporary credentials as environment variables that I can use as long as the shell is running and the session has not expired.

**Comment by AlainODea** [comment]
There is another option.

Run `okta-aws default sts get-caller-identity` to set up stored credentials for the default role and print out what role that is.

Run `aws s3 ls` or other AWS CLI commands to use the default role as stored.

**Comment by brentbain** [comment]
I use the last option - I have a okta-aws being called from a bat file on my desktop - I double click and it sets "default" - then I can launch powershell aws tools or cli (on a windows machine). I also found it useful to do this for each AWS account I connect to - as I run ElasticBeanstalk (EB CLI) for one account a lot - this method allows me to set the EB CLI profile when I run the EB bat file - and then run EB as normal. Took a little to get set up, but now that it's working - I have several others using this method at my org as well.

**Comment by mh-psaad** [comment]
> There is another option.
> 
> Run `okta-aws default sts get-caller-identity` to set up stored credentials for the default profile and print out what role that is.
> 
> Run `aws s3 ls` or other AWS CLI commands to use the default role as stored.

This is what I'm doing. If that is the intended behavior, perhaps the documentation should reflect it as an alternative use case in 'Usage'

**Comment by stevembo** [comment]
> I use the last option - I have a okta-aws being called from a bat file on my desktop - I double click and it sets "default" - then I can launch powershell aws tools or cli (on a windows machine). I also found it useful to do this for each AWS account I connect to - as I run ElasticBeanstalk (EB CLI) for one account a lot - this method allows me to set the EB CLI profile when I run the EB bat file - and then run EB as normal. Took a little to get set up, but now that it's working - I have several others using this method at my org as well.

I would love to know how you got EB CLI working with this? i am facing a similar issue
