### ISSUE TITLE
Installer does not work on fish shell

### ISSUE THREAD

**Issue by patrickf3139** [oktadeveloper/okta-aws-cli-assume-role#234]
**Describe the bug**
All I know for sure is that after following the install instructions, I cannot execute `okta-aws`. I've been debugging and I already notice one huge bug, which is that the installer added
```
export PATH="$HOME/bin:$PATH"
```
to my `config.fish`. That syntax is valid in `bash`, but in fish it should probably be
```
set -x PATH $HOME/bin $PATH
```
Furthermore, it didn't even create a `/bin` folder in my `$HOME` directory.

**To Reproduce**
1. Install the fish shell
2. Execute
```
curl 'https://raw.githubusercontent.com/oktadeveloper/okta-aws-cli-assume-role/master/bin/install.sh' | bash
```
3. Check your `config.fish`

**Comment by AlainODea** [comment]
Good catch. This is an easy fix. The line can be removed. It doesn't make sense anymore since PREFIX  defaults to /usr/local.

**withokta** lands in **/usr/local/bin** and **okta-aws** is created as a shell function.

**Comment by patrickf3139** [comment]
I don't think it's as simple as that. I cleaned everything up, ran the installer again, removed that line, and tried to execute okta-aws:
```sh
okta-aws test sts get-caller-identity
Error: Could not find or load main class com.okta.tools.WithOkta
```
