### ISSUE TITLE
OracleJDK to OpenJDK fix for license issue

### ISSUE THREAD

**Issue by jeugene** [oktadeveloper/okta-aws-cli-assume-role#238]
This codebase uses JavaFX (or another oracleJDK specific jar). 
As you know, Oracle is starting JDK license model in 2019.

My understanding is this specific library is only used in a custom configuration to pop web browser client. We don't use this and have no need for this feature.

Anyone know the specific details to use alternate library or process and make this codebase openJDK8 compliant?

Thanks
Joe

**Comment by AlainODea** [comment]
OpenJFX is bundled with the release. It is GPLv2 with the classpath exception:
https://github.com/javafxports/openjdk-jfx/blob/develop/LICENSE

> OpenJFX is free software, licensed under the GPL with the class path exception, just like the OpenJDK.
SOURCE: https://openjfx.io/

My understanding is that there is no problem with bundling OpenJFX in this manner.

I am not a lawyer.

**Comment by AlainODea** [comment]
I am running this on AdoptOpenJDK 11 locally without issues.

**Comment by AlainODea** [comment]
I’m going to guess this is okay and close this.
