### ISSUE TITLE
use HKCU...ProxyEnable in WithOkta() in Install-OktaAwsCli.ps1

### ISSUE THREAD

**Issue by tlynchpin** [oktadeveloper/okta-aws-cli-assume-role#244]
**Describe the bug**
Exception in thread "main" java.net.UnknownHostException: socks=localhost

**To Reproduce**
1. windows
1. manually configure a localhost socks proxy in internet options, notice that browser uses proxy (edge/chrome, not ff) (ssh "dynamic" socks is common)
1. disable the proxy, notice that browser does not use proxy
1. notice that okta-aws-cli-assume-role tries to use the proxy

**Expected behavior**
respects proxy setting like browser.

**Additional context**
I think the registry HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyEnable should be checked. As well the value of HKCU\...\ProxyServer can be "socks=hostname:port".

**Comment by AlainODea** [comment]
Good catch. I'll put in a fix for this.
