### ISSUE TITLE
Enhancement request: support for application-level MFA sign on policies

### ISSUE THREAD

**Issue by johnsmyth** [oktadeveloper/okta-aws-cli-assume-role#25]
We use application level sign on policies to enforce MFA for specific applications, however the cli tool doesn't support this.  I saw an closed issue from August due to lack of API support.  Has this been added to the API?   Is there some other solution to this problem?

**Comment by joelfranusic-okta** [comment]
Okta still does not have API support for app level MFA. That said, one could _technically_ add support for app level MFA by implementing a HTTP user agent in code that is aware of the MFA prompt that Okta presents.

If you are an Okta customer and would like API support for app level MFA, I suggest reaching out to your support contact at Okta so they can pass your request along to Okta's product team.

**Comment by duhaas2015** [comment]
I'm assuming this example also speaks to if we say have RSA enabled on our AWS application and want to get keys for that app that has MFA enabled on it.  Today, if I disable the MFA on the AWS application it works just fine

**Comment by vorton77** [comment]
Now that Okta has API support for app level MFA, are there plans to upgrade this code to leverage application level sign on policies?

**Comment by rdegges** [comment]
If anyone wants to submit a PR to add that functionality, I'll happily merge it.

Right now this project doesn't have a dedicated maintainer (except me): and I'm not a java developer. I'm just on here triaging community work to keep things going.

**Comment by AlainODea** [comment]
@rdegges I am trying to develop a PR for this. I don't think this is a supported interaction. I have case 00366942 open with developer support.

If I remove the app sign-on policy (or make it not apply to me), I get the expected response HTML page with a SAMLResponse and RelayState and JS to POST it to the ACS.

If I reapply the app sign-on policy, I get an unexpected response HTML page with the generic Okta Org signin page for my org.

This seems like a bug since I've already authenticated to Okta with a factor and I'm providing the resulting valid sessionToken in the request.

Is this a bug? How do i fix this?

**Comment by AlainODea** [comment]
@rdegges disregard. This is unsupported by the Okta Platform.
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/24#issuecomment-350345433

I'll revisit if the OIDC support makes this possible.

**Comment by AlainODea** [comment]
Once there is a release based on #109, you should be (in principle at least) able to get application-level MFA working. If you want this prior to that point, you can build master using maven and try it.

**Comment by AlainODea** [comment]
My colleague pointed out that my solution to this is incomplete. It will not crash on subsequent MFA challenges within the same session (if you set every time or some time lower than the Okta session timeout) when invoking the Amazon Web Services application. You'll need to delete **~/.okta/cookies.properties** if you encounter this. Sorry about that.

**Comment by philliphayesiam** [comment]
Is there an update on this? We have centralized all of our AWS accounts under one Okta AWS application and would like to leverage application level MFA.

**Comment by duhaas2015** [comment]
We're also are looking for any updates on this particular topic.  We've had to enable okta verify at the org level which is fine,  but would prefer to avoid if possible and just enforce mfa at the aws application.

**Comment by AlainODea** [comment]
The problem with the current implementation is that session reuse doesn’t support re-authentication or prompt for MFA.

A workaround is **OKTA_ENV_MODE=true** and **OKTA_BROWSER_AUTH=true**. It does primary auth via the browser every time it runs and supports app-level MFA.

Fixing app-level MFA mainly requires browser auth. I think the solution involves detecting the auth error and launching browser auth with the cookies set with the Okta AWS app URL as the start page. Anyone willing to tackle that would be making a major contribution to this project.

**Comment by AlainODea** [comment]
@philliphayesiam @duhaas2015 I have a PR (#240) to fix this now. Please test it and post a code review and I'll cut a release with this included.

**Comment by duhaas2015** [comment]
Can you please confirm that in order to take advantage of this functionality we need to set:

OKTA_BROWSER_AUTH=true

**Comment by AlainODea** [comment]
Yes, you need to set OKTA_BROWSER_AUTH=true to use app-level MFA. You also need to be running v1.0.6 or later.

**Comment by duhaas2015** [comment]
Appreciate the feedback, now I just need to figure out and understand why when I enable browser it just hangs here:  

[okta hanging](https://i.imgur.com/tE5YWcH.png)

When I specify false for the auth I can authenticate just fine.

**Comment by duhaas2015** [comment]
Pulls up as expected, prompts for MFA

**Comment by AlainODea** [comment]
@duhaas2015 does your browser have a SOCKS or HTTP proxy enabled?

**Comment by duhaas2015** [comment]
Yeah, nothing proxy related, not sure if its something related to our OKTA SSO server on-prem, when i attempt to use it outside the company walls where I have to put my username/password in, it works fine.  OnPrem our okta sso just passes us through based on who we are signed in with locally.

**Comment by AlainODea** [comment]
It’s probably attempting IWA and getting stuck for some reason. Have you tried with the latest 1.8 and 11 JREs. One of them should handle IWA properly. I don’t have an environment to test that, unfortunately.

**Comment by duhaas2015** [comment]
working with our java developer, he put in some additional logic to catch some exceptions and it appears its complaining about the ssl handshake.  When we run the code from intellij it works fine, when we run it outside of intellij it hangs.  Working on fix, will share with folks once we know a bit more.
