### ISSUE TITLE
OKTA_AWS_ROLE_TO_ASSUME does not work with OKTA_BROWSER_AUTH

### ISSUE THREAD

**Issue by ryno75** [oktadeveloper/okta-aws-cli-assume-role#254]
**Describe the bug**
If you are using OKTA_BROWSER_AUTH (for MFA purposes) and have an assertion with multiple roles presented to you and you supply a role name in the OKTA_AWS_ROLE_TO_ASSUME it is not used and you are still prompted for input.

**Comment by AlainODea** [comment]
I can reproduce this if I have a typo, a leading space, or a trailing space in OKTA_AWS_ROLE_TO_ASSUME.

Are any of those the case for your situation?

**Comment by ryno75** [comment]
Thanks for reaching out quickly!
Here is literally what I have...
`OKTA_AWS_ROLE_TO_ASSUME=okta-AWS-SS-CloudAdmin`

**Comment by AlainODea** [comment]
Ah okay.

Role names alone aren't supported.

**OKTA_AWS_ROLE_TO_ASSUME** needs to be a full IAM Role ARN like:
**arn:aws:iam::123456789012:role/okta-AWS-SS-CloudAdmin**

If you replace **123456789012** with your real account number, it should work.

This is not described properly in README.md. I'll keep this open until the readme is updated to be more specific.

Thank you for reporting this.

**Comment by ryno75** [comment]
ohhhhh... I _thought_ about trying the ARN but.. from everything I was seeing and the verbiage of "ROLE" I just figured... nah, its gotta be the role name.  Doh.

**Comment by AlainODea** [comment]
No worries. I've fixed the readme now. Hopefully, the new wording is clearer 😃

**Comment by ryno75** [comment]
The problem with requiring the ARN instead of just the role name is that it makes the setting less re-usable across multiple accounts/roles.  If you changed it to use the role name and simply constructed the ARN from that it would make assuming the same role across numerous accounts possible.

**Comment by AlainODea** [comment]
That is a cool idea. If you're up for implementing it and testing it, I can review and merge it.

The goal of using ARNs was to support many AWS accounts at once with a single Okta app. That is how my colleagues and I use it at work.

In the meantime, you can use a script like this to get role lists:
```shell
okta-listroles | jq '.[] | "\(.accountName),\(.roleOptions[].roleArn)"' --raw-output
```

That will yield output like this:
```shell
Account: account-alias (123456789012),arn:aws:iam::123456789012:role/EC2-Admins
```

With some awk or fc magic you could make a role/account switcher around the outside of the existing tool 😃
