### ISSUE TITLE
list-roles doesn't work with just one role

### ISSUE THREAD

**Issue by robkinyon-roivant** [oktadeveloper/okta-aws-cli-assume-role#255]
**Describe the bug**
If someone only has one role, then tools.ListRoles returns back `[]` instead of the single role the person has.

If someone has more than one role, then ListRoles returns back all the roles (as expected).

**To Reproduce**

**Expected behavior**

I expect ListRoles to always return the roles a person has.

**Screenshots**

**Additional context**

This prevents me from writing out someone's `~/.aws/config` with their default role setup to use CredentialProcess if they only have one role because I don't know what role to assume.

**Comment by AlainODea** [comment]
Interesting issue, @robkinyon-roivant. This is definitely frustrating. The technical reason for this is that listroles currently depends on the AWS SAML signin page. If there is a single role, AWS does not present this page.

okta-credentialprocess should work with a blank or unprovided roleArn

**Comment by robkinyon-roivant** [comment]
I confirm that works. This means my generation of the `~/.aws/config` file depends on whether the response from list-roles has any elements or not.

Please add that to the documentation as a possible response (and why) and that CredentialProcess doesn't require one. At that point, this issue can be closed.

**Comment by AlainODea** [comment]
I will do that. Thank you for reporting this, @robkinyon-roivant.

I’m also going to look into intercepting and decoding the SAMLResponse in the single-role case. If it’s practical, I’ll solve this that way and remove the need for a workaround on your side.
