### ISSUE TITLE
Enhancement request: Proxy Support

### ISSUE THREAD

**Issue by kinux** [oktadeveloper/okta-aws-cli-assume-role#26]
First off, thanks for this great tool. It greatly simplifies the AWS STS interaction.

Our company uses an explicit proxy to access the Internet. I can't find a way to have this program use the proxy, and thus it simply fails when running on our internal network.

I've tried setting the proxy in the traditional way via environment variables, as well as via the traditional JAVA way with -Dhttps.proxyHost directives and neither approach seems to work.

`export http_proxy="http://usrname:passwrd@host:port"`

`java -Dhttps.proxyHost=proxy.global.dish.com -Dhttps.proxyPort=8080 -Dhttps.proxyUser=firstname.lastname -Dhttps.proxyPassword=Dish1234! -classpath .:oktaawscli.jar:../lib/aws-java-sdk-1.11.37.jar com.okta.tools.awscli`

Is Proxy Support built-in and I'm just missing it? If it's not built-in, what are the chances it could be incorporated?

**Comment by kinux** [comment]
Just saw that issue #1 and PR fa718fb91533ebc143326e29a31e47de942171f1 are related to this enhancement

**Comment by AlainODea** [comment]
Proxy support was added in https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/62

@mraible another issue down 🎉
