### ISSUE TITLE
java.lang.IllegalStateException on MFA_CHALLENGE when using push

### ISSUE THREAD

**Issue by vbabenkoru** [oktadeveloper/okta-aws-cli-assume-role#262]
**Describe the bug**
After `validateStatus(jsonObjResponse);` was added to `verifyAnswer` in #250, it started failing on push challenge requests with this error:
```
Push Factor Authentication
Exception in thread "main" java.lang.IllegalStateException: Handling for the received status code is not currently implemented.
The status code received was:
MFA_CHALLENGE: The user must verify the factor-specific challenge. POST to the verify link relation to verify the factor.
```

**To Reproduce**
1. Call 
2. Request Push authentication
3. See the error

**Expected behavior**
It should work, as it did before the latest version.

**Comment by AlainODea** [comment]
Good catch. The MFA handling code in here is a mess. I’ll take a look at correcting this. Thank you for isolating this and reporting it.

**Comment by AlainODea** [comment]
I have a fix I think should work, but I can't see any option to enable Okta Push so I don't have a way to verify that it works.

![Multifactor Authentication page in Okta Admin](https://user-images.githubusercontent.com/16341/51067067-43c41d00-15e9-11e9-8887-7d46a6d2ecd1.png)

Where do you enable Okta Push authentication?

**Comment by vbabenkoru** [comment]
I may be able to test it for you if you open a PR/push to a branch. Push 2FA was enabled for us by our Security team, and I'm not sure how that is set up.
