### ISSUE TITLE
Help with Docker process

### ISSUE THREAD

**Issue by trevor-carlson1** [oktadeveloper/okta-aws-cli-assume-role#278]
**Describe the bug**
When running docker method I keep getting "An error occurred (AccessDenied) when calling the AssumeRole operation: Access denied" but do not get this error when running tool locally. Do I need to change something in my AWS role trust policy in order the for the docker method to work? I feel like there's gotta be a simple fix to this. Thanks so much for the help. 
<img width="1655" alt="screen shot 2019-03-03 at 5 21 17 pm" src="https://user-images.githubusercontent.com/29289571/53705390-fdb15b80-3dd8-11e9-9828-e4756e751d1f.png">

**Comment by AlainODea** [comment]
I think the Docker container has an outdated release.

As a result, it still writes ~/.aws/config and requires that the IAM Role allow AssumeRole on itself. The Docker image should probably be rebuilt with a recent release like v1.10. It’s disconnected from this project and not an official release.

**Comment by trevor-carlson1** [comment]
Ok thanks so much for the quick reply Alain. Really appreciate it.
