### ISSUE TITLE
Null pointer exception if not running from the .okta directory

### ISSUE THREAD

**Issue by glauber-experian** [oktadeveloper/okta-aws-cli-assume-role#279]
**Describe the bug**
I get a Null Pointer Exception when running okta-aws, unless i run it from the $home/.okta directory.

**To Reproduce**

PS C:\work> okta-aws
Exception in thread "main" java.lang.NullPointerException
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at java.net.URI.create(Unknown Source)
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
        at com.okta.tools.saml.OktaAppClientImpl.launchApp(OktaAppClientImpl.java:40)
        at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsRefresh(OktaSaml.java:61)
        at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:47)
        at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:130)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:100)
        at com.okta.tools.WithOkta.main(WithOkta.java:28)

**Expected behavior**

I expect to be able to run okta-aws from any directory.

If i cd to the directory where the configuration files are, it works as expected

PS C:\work> cd .okta
PS C:\work\.okta> okta-aws

Please choose the role you would like to assume:
...

**Additional context**

Windows 7 

$psversiontable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by AlainODea** [comment]
Thank you for your report, @glauber-experian.

The commands included with this tool are designed to be able to be run from any directory. They load config.properties from directory called .okta within your user profile or user home directory. For this to work as you expect, C:\work would have to be your user profile or user home directory. I think that's unlikely.

If you run the following in PowerShell, what does it return?

```powershell
Write-Host $HOME\.okta
```

**Comment by glauber-experian** [comment]
Thank you for looking into this.


PS C:\> write-host $HOME\.okta
c:\work\.okta

**Comment by AlainODea** [comment]
I stand corrected.

It looks like OKTA_AWS_APP_URL is not defined in config.properties.

Do you have OKTA_AWS_APP_URL and OKTA_ORG defined in $HOME\.okta\config.properties?

Here’s a minimal example for the demo Okta Org:
```properties
OKTA_ORG=acme.okta.com
OKTA_AWS_APP_URL=https://acmecorp.oktapreview.com/home/amazon_aws/0oa5zrwfs815KJmVF0h7/137
```

**Comment by glauber-experian** [comment]
I do

Here’s what I have:

OKTA_ORG=experian.okta.com
OKTA_AWS_APP_URL=https://[redacted]
OKTA_USERNAME=ms145gr
OKTA_BROWSER_AUTH=true
OKTA_ENV_MODE=false
OKTA_PROFILE=exp-glauber

**Comment by AlainODea** [comment]
I think the tool can’t find your config.properties. That is possibly due to Java’s value for user.home not being C:\work.

Java sets user.home as follows:

> System property `user.home` is set by:
>
> 1. Read the registry value for key: >`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Desktop`
> 1. Take the parent path of this value, but do *not* resolve environment variables.

SOURCE: https://stackoverflow.com/a/16889969/154527

A workaround is to set environment variables matching config.properties.

```powershell
$env:OKTA_ORG=experian.okta.com
$env:OKTA_AWS_APP_URL="https://[redacted]"
$env:OKTA_BROWSER_AUTH=true
okta-aws exp-glauber sts get-caller-identity
```

This is making me consider addition fine/finer/finest logging statements to track things like config loading and config sources.
