### ISSUE TITLE
Windows 10 Error: The term 'okta-aws' not recognised in a new session.

### ISSUE THREAD

**Issue by mattlawnz** [oktadeveloper/okta-aws-cli-assume-role#291]
**Describe the bug**
After following the Install instructions for Windows, the program worked fine. Whenever we close & re-open, or even open a new cmd session, we run into the error above.

**To Reproduce**
Open a new window
run ```okta-aws test sts get-caller-identity```
To get it working again, run the install command again

**Expected behavior**
Id expect this not to happen

**Screenshots**
![image](https://user-images.githubusercontent.com/30304027/56165631-8dc50080-6027-11e9-8db5-3d207410af13.png)

**Additional context**
I thought it might have somethign to do with the execution policy of the machine, but this is the result:
PS H:\> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine       Undefined

**Comment by junkangli** [comment]
On Windows, the `okta-aws` is an alias defined in the current user, current host PowerShell [$profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6#the-profile-variable). Based on the error message in your screenshot, it appears that the `okta-aws` alias is missing in your PowerShell profile. To further troubleshoot, you can run the below command to get the contents of your profile and check that the alias is defined:
```
Get-Content $Profile
```
The alias is put in by the installation script.
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/21e55af63e31a820eb216aac58bdcb146f0e1296/bin/Install-OktaAwsCli.ps1#L117

**Comment by junkangli** [comment]
To attempt to resolve the problem, you may want to consider re-installing from a fresh slate by deleting your `$HOME\.okta` directory and perform the [Windows installation](https://github.com/oktadeveloper/okta-aws-cli-assume-role#windows) step again.

**Comment by mattlawnz** [comment]
Hi

Thanks for the follow up. Seems like it was a group policy setting preventing the running of scripts when opening a new window. We will sort this at our end.
