### ISSUE TITLE
Athena query after first space treated as additional CLI option

### ISSUE THREAD

**Issue by kherrera-ebsco** [oktadeveloper/okta-aws-cli-assume-role#297]
**Describe the bug**

In macOS, when executing a query in Athena, if the query has a space in it, anything following the space will be treated as an additional command line option.

**To Reproduce**

1. Execute `okta-aws live athena start-query-execution --query-string 'SELECT COUNT(1);' --result-configuration '{"OutputLocation":"s3://aws-athena-query-results-012345678901-us-east-1"}'`
4. See error: `Unknown options: COUNT(1);`

**Expected behavior**

AWS response to `start-query-execution`.

**Screenshots**

<img width="1582" alt="Screen Shot 2019-05-15 at 7 01 51 AM" src="https://user-images.githubusercontent.com/25376904/57781927-07601500-76e0-11e9-8f10-b407f968f309.png">

**Additional context**

1. BASH scripts generated by `install.sh` do not properly quote arguments.
    a. [`~/.okta/bash_functions`](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/bin/install.sh#L101): `$@` should be `"$@"`
    b. [`~/.okta/bin/withokta`](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/bin/install.sh#L146): `$@` should be `"$@"`

**Comment by dwrzosSOP** [comment]
Hi, I have the same issue. How to deal with this ?
Everything works fine from aws CLI. The problem is with terraform:
```
provisioner "local-exec" {
command = "aws athena start-query-execution --work-group \"${aws_athena_workgroup.dw_test-wg.name}\" --query-execution-context \"Database=xxx-fis-2-xxxxxx-db,Catalog=AwsDataCatalog\" --query-string \"select 1\" --result-configuration \"OutputLocation=s3://xxx-rd-athena-results\""
     
     }
```
