### ISSUE TITLE
running okta-aws-cli windows 7 error

### ISSUE THREAD

**Issue by Basma1912** [oktadeveloper/okta-aws-cli-assume-role#299]
I am trying to run the command : okta-aws TEST-Admins sts get-caller-identity on windows 7 and I am getting the below error : 

Error: Could not find or load main class com.okta.tools.WithOkta
Caused by: java.lang.ClassNotFoundException: com.okta.tools.WithOkta

![image](https://user-images.githubusercontent.com/12595949/58270011-cb1f5b00-7d56-11e9-9f59-297225d0e6d0.png)

**Comment by junkangli** [comment]
Can you check whether the _okta-aws-cli.jar_ is located under the directory _$HOME/.okta_? You can do it by running the below command:
```
dir $HOME/.okta
```

**Comment by Basma1912** [comment]
@junkangli  - I managed to get this working , I manually downloaded the files , because for some reason the command: Set-ExecutionPolicy -Scope Process -ExecutionPolicy unrestricted -Force; Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/oktadeveloper/okta-aws-cli-assume-role/master/bin/Install-OktaAwsCli.ps1')); .$profile 

was not downloading the .jar files and once i did the tool started to work
