### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by danielcbright** [oktadeveloper/okta-aws-cli-assume-role#3]
I just got this tool working, thanks for putting this up here. I was using a Python based tool we wrote internally that was using `requests`, but doesn't work now that the login page is `JavaScript` enabled. I think the ability to pass in command line arguments, such as profile save name, IdP app url, region, output format (for the credentials file) would be awesome. Just wanted to pass that on.

Great work!

**Comment by raphaellondner-okta** [comment]
Hi Daniel, thanks for the nice feedback and thank you even more for the enhancement suggestions! Can you clarify what you mean by "IdP app url"? Also, I assume you are referring to the config file for the region, output arguments and both to the credentials and config file for the profile save name. Is that correct?

**Comment by danielcbright** [comment]
Hi Raphael, 

By IdP App URL I mean the `OKTA_AWS_APP_URL` variable. Currently we can iterate over multiple accounts using a `for` loop if we want and execute some `aws cli` command across multiple accounts. I'd like to avoid having to write a wrapper script to update the `config.properties` file with the new URL each time we iterate, it just makes it cleaner to be able to pass in the same variables as command line arguments.

And as far as the other arguments, profile save name, output format, region, this is what I envision being able to do:

```
java -DOKTA_ORG=test.okta.com -DOKTA_AWS_APP_URL=https://test.okta.com/appurl -DAWS_REGION=us-east-1 -DAWS_OUTPUT=json -DAWS_PROFILENAME=some-name -classpath oktaawscli.jar:$HOME/Projects/okta-aws-cli-assume-role/lib/aws-java-sdk-1.11.25.jar:$HOME/Projects/okta-aws-cli-assume-role/lib/okta-sdk.jar com.okta.tools.awscli
```

Does that make sense? see how that can be used in a script to easily iterate over multiple accounts (we have a ton).

**Comment by radekg** [comment]
Partially addressed with https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/9

**Comment by raphaellondner-okta** [comment]
Thank you for this suggestion, which we are marking as an enhancement request for a future version of the tool (since it's not an issue per se).

**Comment by AlainODea** [comment]
This is possible as of #78.

@mraible this can be closed.
