### ISSUE TITLE
macOS specific command in Readme.MD

### ISSUE THREAD

**Issue by pmccarthy01** [oktadeveloper/okta-aws-cli-assume-role#30]
The following line in Readme.MD is macOS specific. It should probably note that, and if there is an equivalent command for Windows, that should probably be added.

> In Terminal, run defaults write com.apple.finder AppleShowAllFiles YES if you want to be able to inspect the ~/.aws/credentials and ~/.aws/config files.

**Comment by AlainODea** [comment]
@pmccarthy01 we accept pull requests. That's a good opportunity for a contribution 😄
