### ISSUE TITLE
Support multiple named AWS profile names

### ISSUE THREAD

**Issue by hecsalazar** [oktadeveloper/okta-aws-cli-assume-role#304]
Currently the tool supports only one AWS profile name in config.properties file

For devops that work usually with more than one AWS account, the only option is to not specify an AWS profile name and let the tool create a profile with the name of the Role ARN which is not very human friendly.

Requested feature:
Provide a mechanism via command line where we can specify an AWS profile name for the aws credentials. Ex:
okta-aws --aws-profile dev-project1
okta-aws --aws-profile prod-project1

Benefit:
The users with multiple account names can use meaningful and easy to remember profile names when working with multiple AWS accounts.

**Comment by junkangli** [comment]
Currently, we can set the name of the AWS profile to create by specifying the parameter `OKTA_PROFILE`.
For my case, to configure multiple AWS accounts, I created multiple applications in OKTA. As a result, in my _config.properties_ file, there are multiple `OKTA_PROFILE` and `OKTA_AWS_APP_URL` parameters configured, for example:
```
OKTA_ORG=acmecorp.okta.com.changeme.local
OKTA_USERNAME=junkangli

OKTA_PROFILE=development
OKTA_AWS_APP_URL=https://acmecorp.okta.com.changeme.local/home/amazon_aws/development

#OKTA_PROFILE=production
#OKTA_AWS_APP_URL=https://acmecorp.okta.com.changeme.local/home/amazon_aws/production
```
You may notice only 1 set of `OKTA_PROFILE` and `OKTA_AWS_APP_URL` parameters is active while the rest are commented out. To switch to another account, I will need to toggle the comment lines accordingly.

**Comment by hecsalazar** [comment]
Thanks for the workaround tip.
In our case just a few people use multiple Okta environments, mostly is only the team responsible of the Okta integration.
The most common use case use production Okta auth and multiple AWS accounts.
The intention is to be able to refresh the multiple AWS profiles tokens using human friendly names, or standard nomenclature that devops are more familiar with.
