### ISSUE TITLE
Array Index out of bounds Exception while selecting the assigned Roles from AWS CLI

### ISSUE THREAD

**Issue by laperi** [oktadeveloper/okta-aws-cli-assume-role#306]
When i executed Okta CLI Assume Role tool jar file, it prompted to enter the AWS User credentials. I have given AWS user credentials. The user's assigned Roles have been displayed and one should be selected from them. 
When i select any of the assigned Role, it is throwing below error:

Exception in thread "Main" Java.lang.ArrayIndexOutofBoundsException: 0
at java.lang.ProcessBuilder.start(unknown source)
at com.okta.toolswithOkta.main(WithOkta.java:41)

If anyone faced similar issue, your comments are very much helpful. 

Thanks in advance!!

**Comment by jralmaraz** [comment]
+1 having the same issue in MacOS :(
