### ISSUE TITLE
Consolidate/Finalize portable package building

### ISSUE THREAD

**Issue by thefotios** [oktadeveloper/okta-aws-cli-assume-role#32]
There are a number of outstanding/closed PRs and issues around artifact building. Is there any interest from the maintainers on integrating this? If there is, I would be happy to try to shepherd those changes into a single PR with the help from the original submitters.

Related:
- #19 
- #31 
- #27 
- #12 
- #9

**Comment by mmahadevan-okta** [comment]
@thefotios Just a quick note to acknowledge the comment/issue. /cc @johngronberg-okta @joelfranusic-okta

**Comment by AlainODea** [comment]
@mraible this can be closed.

The build enhancements from the PRs highlighted have all been merged.
