### ISSUE TITLE
2.0.3 with one role won't write credentials file

### ISSUE THREAD

**Issue by snoopytrb** [oktadeveloper/okta-aws-cli-assume-role#328]
**Describe the bug**
Using 2.0.3 if you only have one role available the java window will log into the console instead of writing the token back to the .aws/credentials file

**To Reproduce**
1. Run okta-aws tool as normal, sign in with MFA
2. If you only have one role the java window will continue through to the console instead of closing and writing the credentials file.

**Expected behavior**
If only one role is available tool should automatically write that role to the credentials file.

**Comment by jeremyplichtafc** [comment]
I have seen this in our organization as well and have started looking into it. Stay tuned for fix. Hopefully soon 🤞
