### ISSUE TITLE
config.properties does not appear to be respected in the "out" directory

### ISSUE THREAD

**Issue by thefotios** [oktadeveloper/okta-aws-cli-assume-role#33]
The directions in https://github.com/oktadeveloper/okta-aws-cli-assume-role#configuring-the-application do not work. This only seems to work if `config.properties` is in the CWD when you execute the script.

I believe #14 fixes this.

**Comment by AlainODea** [comment]
@mraible this issue is fixed 🎉

**Comment by AlainODea** [comment]
This is fixed.

@mraible this can be closed.
