### ISSUE TITLE
How to force download fresh copy of the temporary keys or re-authenticate 

### ISSUE THREAD

**Issue by ineedimprov** [oktadeveloper/okta-aws-cli-assume-role#363]
If I setting OKTA_STS_DURATION=7200, download the temporary keys, but later want to kill this session or download a new copies, is this possible? 
I tried to delete the cookies.properties, profiles, and the aws credentials files but it not seem to work (I don't get the authentication prompt).

**Comment by jeremyplichtafc** [comment]
in addition to those two files try removing the `.current-session` file as well in the same directory

**Comment by ineedimprov** [comment]
Thank you it working.
