### ISSUE TITLE
IAM Role inside a "folder"

### ISSUE THREAD

**Issue by duhaas2015** [oktadeveloper/okta-aws-cli-assume-role#37]
I have an iam role that looks like:

arn:aws:iam::XXXXXXX:role/aplp/Role-IT-PlatformTeam

Noticed i used "aplp" as a "folder" to store all our roles moving forward.  The issue I'm having is the cli seems to not like the fact that it sees it as aplp/Role-IT-PlatformTeam now, that by design or???

[http://i.imgur.com/jIJNnti.png](url)

**Comment by AlainODea** [comment]
@mraible this is resolved by #73, which is now merged.
