### ISSUE TITLE
Configurable session duration

### ISSUE THREAD

**Issue by liquid-sky** [oktadeveloper/okta-aws-cli-assume-role#38]
It's possible to configure session duration in the UI and should be also possible to configure it using CLI tool. Can be done by parametrising [this line](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/src/main/java/com/okta/tools/awscli.java#L423).

**Comment by AlainODea** [comment]
This is a good idea.

@smashling configurable session duration is a good one for your backlog after you get named sessions, multiple concurrent sessions, and Okta session reuse for those done. Probably something to consider in late Feb or early March.

**Comment by AlainODea** [comment]
Unfortunately, session duration cannot be controlled by a client, which this acts as.

The session duration is controlled by the Amazon Web Services app in the Sign On tab as the **Session Duration (Required only for SAML SSO)** setting. It cannot be altered by a client.

@mraible this can be closed as a documented fix.

**Comment by ctoa** [comment]
@AlainODea I was testing this and __Session Duration (Required only for SAML SSO)__ seemed to only affect AWS console, but not the CLI. E.g. I set  __Session Duration (Required only for SAML SSO)__  to `900` and I get kicked out from AWS console after 15 mins, but the CLI still works for 1 hr.

**Comment by AlainODea** [comment]
Oh. That’s concerning!

Thank you for finding this. That works differently than I expected.

It creates an opportunity here that I’ll investigate in a few weeks when I get time.

**Comment by ctoa** [comment]
@AlainODea Did you know if someone manage to take a look at this? Thanks!

**Comment by AlainODea** [comment]
@ctoa you are correct. You should try #111. It should fix your issue.

**Comment by AlainODea** [comment]
@mraible this is not fixed. Confirmed today that the sessions are bound by the 3600 second limit hardcoded in this codebase.

This should be reopened pending #111.
