### ISSUE TITLE
Can't seem to run on Windows

### ISSUE THREAD

**Issue by danielcbright** [oktadeveloper/okta-aws-cli-assume-role#4]
Hi,

I have an issue when trying to run this on a Windows 7 box, here is the error I'm getting:
```
\java -classpath oktaawscli.jar:../lib/aws-java-sdk-1.11.27.jar com.okta.tools.awscli
Error: Could not find or load main class com.okta.tools.awscli
```
I have a feeling it's a syntax error but not sure, help would be appreciated.

**Comment by raphaellondner-okta** [comment]
Hi Daniel,

Have you tried to use the Windows batch file? https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/out/awscli.bat

**Comment by raphaellondner-okta** [comment]
Closing this issue as it has been fixed in the awscli.bat file mentioned in the previous comment.
