### ISSUE TITLE
Enhancement request: Show account name/alias instead of account number

### ISSUE THREAD

**Issue by opragel** [oktadeveloper/okta-aws-cli-assume-role#40]
Right now when selecting a role to assume, we are shown account numbers instead of the account name/alias if it exists. Since most of our users won't recognize the account number immediately, this means we have to make which account each role is part of clear in the role name itself. Wouldbe nice to have the account names listed instead so we could avoid that.

**Comment by AlainODea** [comment]
This was fixed in https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/57 . The current version shows a friendly menu with account aliases if they are available.

@mraible another bug bites the dust 🎉
