### ISSUE TITLE
AssumeRoleWithSAMLRequest doesn't seem to work with China (Beijing) region or GovCloud

### ISSUE THREAD

**Issue by joelfranusic-okta** [oktadeveloper/okta-aws-cli-assume-role#43]
From the AWS docs:

> The default AWS Security Token Service (STS) endpoint ("sts.amazonaws.com") works for all accounts that are not for China (Beijing) region or GovCloud. You only need to change the endpoint to "sts.cn-north-1.amazonaws.com.cn" when you are requesting session credentials for services in China(Beijing) region or "sts.us-gov-west-1.amazonaws.com" for GovCloud.

[source](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSSessionCredentialsProvider.html#setSTSClientEndpoint-java.lang.String-)

A quick fix, I think, would be to add the (deprecated) [`withServiceEndpoint`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.Builder.html#withServiceEndpoint-java.lang.String-) builder to the code below:

https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/4dbfb4a7d7ddfb85e5567781d55e3736421c9282/src/main/java/com/okta/tools/awscli.java#L419-L423

Longer term, we should move the code to use to the [AWSSecurityTokenServiceClientBuilder ](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClientBuilder.html)

**Comment by AlainODea** [comment]
This is interesting. I got us partway there by using **AWSSecurityTokenServiceClientBuilder** and then destroyed that by hard-coding US-EAST-1 🤕 I'm putting this on my backlog to fix.

**Comment by Joeskyyy** [comment]
Hey @AlainODea is https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/131 supposed to be a fix for this? I wasn't able to get that fork working for GovCloud either :\ Looks like that fork still has the AWSSecurityTokenServiceClientBuilder pointing to `Regions.US-EAST-1`

Any work on when a fix could be coming for that? Major issue for us using Okta and AWS right now

**Comment by AlainODea** [comment]
@Joeskyyy no. That fix covers profile regions, but not STS regions.

It would be straight-forward to springboard off that fix to fix this since it adds **awsRegion** to **OktaAwsCliEnvironment**. That could be used directly to set the region used for STS.

Are you up for developing, testing, and contributing that?

**Comment by Joeskyyy** [comment]
Yeah, I was toying around a bit yesterday with the variable available in `OktaAwsCliEnvironment` but my java foo is rusty and was running into some issues haha

I was trying a rudimentary if/else block around the connection and not getting any luck. Oddly enough, even when I compiled a JAR with an explicit `Regions.GovCloud` I received issues, granted it wasn't the same one I was getting before, I believe it had an invalid token or something. I can try and dig again but as I'm sure we all are, a bit stretched thin at the moment.

**Comment by AlainODea** [comment]
@Joeskyyy I think you're right. It probably has to do with the region written to ~/.aws/config rather than this tool once **RoleHelper** is fixed and #131 is merged.

Do you want to roll up your **RoleHelper** fix into a PR?

**Comment by Joeskyyy** [comment]
@AlainODea I'm actually still not having success with changing `RoleHelper` ): I tried changing it explicitly in the example above to `.withRegion(Regions.GovCloud)` and it was passing the `client_region` to us-east-1. To be fair, I didn't test this off a fork of #131, but we wouldn't want those changes in a PR since it wouldn't solve the actual problem.

I'm thinking after #131 is merged, since we'll have the region as part of what can be passed in, there would need to be a `Regions` helper to actually return the region object itself based off the name?

**Comment by AlainODea** [comment]
@Joeskyyy did you have any luck with this after?

**Comment by Joeskyyy** [comment]
@AlainODea sorry I did not, got distracted by dozens of other things haha I'll see if I can dedicate some time next week to this...

**Comment by Joeskyyy** [comment]
@AlainODea So it looks like `awsRegion` was removed? https://github.com/oktadeveloper/okta-aws-cli-assume-role/commit/65804120bfb7acfa38936ce6f4b7a05b3d7e23d3#diff-c543fc080eb0d7666d5554a7b0093a3f

So now `private OktaAwsCliEnvironment environment` doesn't have a region to pull from.

The only place region is now being referenced is in `OktaAwsConfig` in `getAwsRegionOrDefault()` but that region method can't be accessed from outside the class.

**Comment by AlainODea** [comment]
@Joeskyyy is pulling from the [AWS CLI's **AWS_DEFAULT_REGION** environment variable](https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html) a workable alternative for your code?

**Comment by Joeskyyy** [comment]
@AlainODea  https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/227

I think pulling the variable was a bad design decision. I reverted b86dc34 and built upon it. Was able to successfully get it working.
