### ISSUE TITLE
What to do when there is no AWS configuration

### ISSUE THREAD

**Issue by boyvanduuren** [oktadeveloper/okta-aws-cli-assume-role#49]
Recently #48 was merged. These changes make sure default profiles will not be overwritten.
However, I was wondering what we should do when there aren't any `$HOME/.aws/config` and `$HOME/.aws/credentials` configuration files yet.

Maybe we should write the newly created profile as a default profile in case there is no previous aws-cli credentials configuration, and add/update it if there is.
That way people that use only this tool to set up aws-cli configuration will have a usable default profile, and people that had already setup aws-cli configuration will have their default profile kept intact.

The current version will just write an empty (unusable) default profile in addition to the newly generated profile if there is no previous aws-cli config.

**Comment by rdegges** [comment]
I think that sounds like a reasonable solution.

**Comment by boyvanduuren** [comment]
Great! :) I've just created a PR.

**Comment by rdegges** [comment]
Merged!
