### ISSUE TITLE
Null Pointer Exception in Main

### ISSUE THREAD

**Issue by jbruettcva** [oktadeveloper/okta-aws-cli-assume-role#5]
Great tool, little clunky to setup but it works and it's really smooth once you get there.

I am getting an issue, though it's actually working so I'm a bit confused.

Environment: 
- Windows 10 Anniversary Edition
- aws-java-sdk-1.11.37
- downloaded the zip file from here last week
- run either in a standard powershell or cmd.exe shell i receive the same error/experience
- followed this article for setup/configuration: https://support.okta.com/help/articles/Knowledge_Article/Integrating-the-Amazon-Web-Services-Command-Line-Interface-Using-Okta?retURL=%2Fhelp%2Fapex%2FKnowledgeArticleJson%3Fc%3DOkta_Documentation%253ATechnical_Documentation%26p%3D101%26inline%3D1&popup=true

This output has been scrubbed a little for security

```
[3|2:04 PM|+1ms] [...\okta-aws-cli\out]
> .\awscli.bat

C:\users\jbruett\Documents\okta-aws-cli\out>java -classpath oktaawscli.jar;../lib/aws-java-sdk-1.11.37.jar com.okta.tool
s.awscli
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Username: <username>
Password: <password>

Please choose the role you would like to assume:
[ 1 ]: arn:aws:iam::###########:role/<role1>
[ 2 ]: arn:aws:iam::###########:role/<role2>
Selection: 1
Exception in thread "main" java.lang.NullPointerException
        at com.okta.tools.awscli.GetRoleToAssume(awscli.java:493)
        at com.okta.tools.awscli.main(awscli.java:133)
```

regardless of the error, i have a valid session and the credentials are successfully written to file.  I'm thinking that this is something to do with the ERROR about log4j2, but it's there, so i'm not sure

**Comment by raphaellondner-okta** [comment]
Hi John,

Thank you for reporting that error to us. Please note that this tool, although it was built by Okta, is community-supported and we accept any pull request about code fixes external developers might have.

I looked at the code and it looks like in your case, the code breaks on [line 493](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/src/main/java/com/okta/tools/awscli.java#L493), which means we're making a false assumption about the structure of your role policy "Statement" JSON node.

Is there you could provide the full role policy JSON you have created for your cross-account role?

**Comment by jbruettcva** [comment]
there is no cross account role policy.  My user has access to my account.  That's it, unless I'm missing something.

**Comment by raphaellondner-okta** [comment]
Thanks for the feedback. It looks as if our code thinks there is a role policy attached to role1 and role2. I would advise contacting our developer support at developers at okta dot com to troubleshoot this issue, if there is indeed no role policy attached to these roles. If there are role policies attached to these roles, there is probably something that must get fixed in our tool code.

**Comment by jbruettcva** [comment]
So i was totally wrong, there are two policies on the role that I am selecting.  One is the managed AdministratorAccess delivered by AWS.  Additionally there is a custom policy for VM import/export that is listed below:

{
"Version": "2012-10-17",
"Statement": [
  {
    "Effect": "Allow",
    "Action": [
      "s3:ListAllMyBuckets"
    ],
    "Resource": "*"
  },
  {
    "Effect": "Allow",
    "Action": [
      "s3:CreateBucket",
      "s3:DeleteBucket",
      "s3:DeleteObject",
      "s3:GetBucketLocation",
      "s3:GetObject",
      "s3:ListBucket",
      "s3:PutObject"
    ],
    "Resource": ["arn:aws:s3:::<BUCKET_NAME>","arn:aws:s3:::<BUCKET_NAME>/*"]
  },
  {
    "Effect": "Allow",
    "Action": [
      "ec2:CancelConversionTask",
      "ec2:CancelExportTask",
      "ec2:CreateImage",
      "ec2:CreateInstanceExportTask",
      "ec2:CreateTags",
      "ec2:DeleteTags",
      "ec2:DescribeConversionTasks",
      "ec2:DescribeExportTasks",
      "ec2:DescribeInstanceAttribute",
      "ec2:DescribeInstanceStatus",
      "ec2:DescribeInstances",
      "ec2:DescribeTags",
      "ec2:ImportInstance",
      "ec2:ImportVolume",
      "ec2:StartInstances",
      "ec2:StopInstances",
      "ec2:TerminateInstances",
      "ec2:ImportImage",
      "ec2:ImportSnapshot",
      "ec2:DescribeImportImageTasks",
      "ec2:DescribeImportSnapshotTasks",
      "ec2:CancelImportTask"
    ],
    "Resource": "*"
  }
]
}

**Comment by johnsmyth** [comment]
I am experiencing the same issue.  I'm not a java programmer, but could it be that it fails when Action is an Array instead of a string?

**Comment by jbruettcva** [comment]
I removed one of my policies and i am no longer receiving the error, but rather the expected reporting output about the credentials being created and their timeout information etc.  @johnsmyth was dead on that it's expecting a string and receiving an array and that's the issue.  Like John, I'm no java developer, I'll take a look and see if i can't figure it out.  Hopefully someone that's more versed than I will get to the fix first! :)

**Comment by raphaellondner-okta** [comment]
Hi John B. and John S.,

Thanks for getting back to me. I have tested with John B.'s statement and made the tool's code more robust to handle Statement arrays. We still do not handle the case when there are multiple policies (we take the first one we find), neither multiple sts:AssumeRole actions in the same statement (we take the first one we find).

**Comment by johnsmyth** [comment]
This seems to be working now - Thanks!

**Comment by raphaellondner-okta** [comment]
This issue appears to be resolved now, so closing it.
