### ISSUE TITLE
Why is the timeout hardcoded?

### ISSUE THREAD

**Issue by jake-gg** [oktadeveloper/okta-aws-cli-assume-role#51]
Why is the timeout hardcoded? Can this be parameterised? If the Okta Application sets a timeout of 8 hours, the CLI tool should respect that.

https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/b8ce7d17fe383fb9c420eb0e0fe7d9a82ea8778e/src/main/java/com/okta/tools/awscli.java#L428

**Comment by mmaha** [comment]
FWIW, the AWS only allows a max of 3600 seconds. https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html 

> The temporary security credentials are valid for the duration that you specified when calling AssumeRole, or until the time specified in the SAML authentication response's SessionNotOnOrAfter value, whichever is shorter. The duration can be from 900 seconds (15 minutes) to a maximum of 3600 seconds (1 hour). The default is 1 hour.

**Comment by rdegges** [comment]
If you'd like to submit a PR to add it as a parameter, I think that's fine.

**Comment by jake-gg** [comment]
Thanks @mmaha for that link. It appears there is no point in parameterising this until AWS allow this to be more than an hour. I'm closing this.

**Comment by jpcollins** [comment]
AWS now allows this to be more than an hour: 
https://aws.amazon.com/about-aws/whats-new/2018/03/longer-role-sessions/

https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role-with-saml.html

See #108 as well.
