### ISSUE TITLE
Support for credential_process

### ISSUE THREAD

**Issue by mmahadevan-okta** [oktadeveloper/okta-aws-cli-assume-role#59]
This was talked about in the recent [AWS CLI talk at re:Invent ](http://awsfeed.com/post/168047446129/aws-reinvent-2017-aws-cli-2017-and-beyond)

By supporting returning a specific JSON object, as described here:  http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes [okta-aws-cli-assume-role](https://github.com/oktadeveloper/okta-aws-cli-assume-role) can integrate better with the [aws-cli](https://aws.amazon.com/cli/) command. 

See example here:  https://github.com/awslabs/awsprocesscreds 

/cc: @AlainODea @mraible @rdegges @joelfranusic-okta

**Comment by AlainODea** [comment]
I really like this idea, @mmahadevan-okta. I'll read into this and see if I can adapt the program to work as a **credential_process** for AWS CLI. That's much cleaner.

My colleagues have been asking how to get this to support other tools like Serverless, ECS CLI, and Terraform. I think your idea is a step in that direction, where it can support whatever downstream tool needs it.

**Comment by mmahadevan-okta** [comment]
Right, I was quite happy to see the support for this.  [Kyle Knapp](https://github.com/kyleknap) and team from AWS own the aws-cli command.

**Comment by etendards** [comment]
Have you guys seen this Chrome extension?  https://github.com/prolane/samltoawsstskeys

I cant get it to work with current version of Chrome.

**Comment by AlainODea** [comment]
@etendards I’m not familiar with that Chrome plugin. You might want to post an issue on their repo.
