### ISSUE TITLE
[enahancement] Support for new extended STS SAML timing

### ISSUE THREAD

**Issue by jbruettcva** [oktadeveloper/okta-aws-cli-assume-role#6]
Wondering if there's a timeline in adding the ability to extend the token to 12 hours per the new functionality in AWS?

**Comment by raphaellondner-okta** [comment]
Hi John,

As mentioned on this [AWS blog post](http://blogs.aws.amazon.com/security/post/Tx3GL3IZE3FIGB6/Enable-Your-Federated-Users-to-Work-in-the-AWS-Management-Console-for-up-to-12-H) (in one of the comments):

> Hi AWS,

> is it possible to extend the Expiration of the Credentials created by the  AssumeRoleWithSaml API Call also from 1h to 12h?  This would make the live of our developers much easier.
> 
> Thanks in Advance
> 
> Wido Franke
> mytaxi
> 

to which the latest comment from the AWS team is:

> Hi Bruce Edge and bmacauley,
> 
> Thanks for the feedback about session duration when using the CLI/SDK. We are aware of this use case and we'll evaluate it for inclusion on our roadmap.
> 
> -Kai, Senior Product Manager, AWS Identity and Access Management

so I guess at this point, we can't really extend the session length past one hour. Or is there something I misunderstood in your question?

**Comment by jbruettcva** [comment]
I've misunderstood the way that AWS builds its services.  I was under the impression that it was API/CLI/SDK first, then pushed to everything else.  Seeing as this is a feature released to the public I would have assumed it was available through the same API that the rest of this tool works with.
