### ISSUE TITLE
User assigned to only one SAML User Role results in No Selection Present

### ISSUE THREAD

**Issue by cyrus-mc** [oktadeveloper/okta-aws-cli-assume-role#66]
From within Okta, a user is assigned to only one SAML User Role. This results in no selections being present yet the prompt to make a selection is still presented. 

Looking at the code it appears to parse the AWL SAML role selection page to determine what to present in that selection. As the user is only assigned to one SAML User Role this selection page isn't presented and the user is dropped right into the Identity account.

**Comment by peterslivka** [comment]
I had the same issue. Checking out older commit 4b78f5a from 20 Dec 2017 helped, so the issue must be introduced in latest changes.

**Comment by AlainODea** [comment]
This is fixed by #68, once that PR is merged, it will pick the single role automatically and not display this broken selection menu.

Sorry about this.

**Comment by AlainODea** [comment]
@mraible another one to close. This has been a fruitful cleanup 🎉
