### ISSUE TITLE
Question: I have multiple roles but if I want to select to one role and then another before my okta session expires

### ISSUE THREAD

**Issue by Maanpreet** [oktadeveloper/okta-aws-cli-assume-role#69]
Thanks for putting up nice tool and I got it working. I have multiple roles but if I want to select to one role and then I want to select another role before my orginal okta session expires, right now if I do this (before expiring old session) ./awscli sts get-caller-identity,   it shows me details for old session rather than prompting a new session.

Please let me know if I'm missing something.

Thanks

**Comment by Maanpreet** [comment]
And also, is it possible to specify multiple app names in config  ?

**Comment by AlainODea** [comment]
There is logout functionality in the JAR in master now (built from #68). That will take you partway.

@smashling is developing support for named profiles and then following that with support for managing multiple named profiles. He should have a PR for named profiles next week.

**Comment by AlainODea** [comment]
I like this idea. Using the same Okta session for multiple profiles would be useful. It would be a big user experience boost over the current approach which requires you to re-authenticate.

I'll see if we can get that done after the multiple profiles work.

**Comment by AlainODea** [comment]
Sorry, #68 isn't merged yet. Once it is, the out/oktaawscli.jar there will include the fix.

**Comment by AlainODea** [comment]
@smashling rereading this, I realize it's a request for reusing the Okta session not just named sessions. It looks like Okta session reuse will solve a lot of user experience problems.

**Comment by AlainODea** [comment]
This was implemented in #83. It has been released.

@mraible this issue can be closed 🎉
