### ISSUE TITLE
Tool uses different home directory than AWS sdk/powershell config process

### ISSUE THREAD

**Issue by jbruettcva** [oktadeveloper/okta-aws-cli-assume-role#7]
I believe that the aws sdk and powershell module put their configuration in %home%.aws.  This tool uses the java variable user.home, which returns the windows variable for %userprofile%.  

I'm no java developer otherwise I would figure out how to get this working and submit the code changes my self.

**Comment by raphaellondner-okta** [comment]
Closing this issue, since the tool has been tested to work on Windows and no specific issue has been reported since.
If a problem comes up, feel free to re-open this issue with more specifics.
