### ISSUE TITLE
Travis CI and releasing to an artifact repository

### ISSUE THREAD

**Issue by AlainODea** [oktadeveloper/okta-aws-cli-assume-role#72]
@mraible I think your suggestion publishing to Maven Central from Travis is a practical solution to this problem.

@loopingz do you agree? S3 is an option, but I think Maven would be easier to discover and consume.

**Comment by AlainODea** [comment]
@mraible having out/oktaawscli.jar in the repository is causing a lot of merging headaches for us during development. It also makes the repository really big when cloning and fetching.

Is there any chance you folks at Okta can set up a Travis CI or similar CI system for building the JAR?

**Comment by mraible** [comment]
@AlainODea I'll work on this today.

**Comment by mraible** [comment]
Release published to https://packagecloud.io/oktadev/okta-aws-cli-assume-role and on GitHub https://github.com/oktadeveloper/okta-aws-cli-assume-role/releases.

**Comment by mraible** [comment]
This will automatically upload new versions when a tag is created. If we want snapshot releases, we'll have to tweak `.travis.yml`. I used [this article](https://blog.travis-ci.com/2017-03-30-deploy-maven-travis-ci-packagecloud/) as a guide.

**Comment by AlainODea** [comment]
Hero of the day!! Awesome work, @mraible 🎉  Thank you.
