### ISSUE TITLE
handle more than 1 policy

### ISSUE THREAD

**Issue by maciekm** [oktadeveloper/okta-aws-cli-assume-role#8]
Hi, any idea when we can expect it?

https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/4aae908451bef7dac8a9d9ac2a8496339fa3a4df/src/main/java/com/okta/tools/awscli.java#L458

Without it we have to one-to-one map policies to roles.

**Comment by raphaellondner-okta** [comment]
@maciekm sorry for the late response. Can you try the latest release in which we've added support for multiple policies? (caveat: only works with single-statement, single-action managed policies, not inline policies).

Let me know if that works for you.

**Comment by raphaellondner-okta** [comment]
Closing this issue due to recent update.
