### ISSUE TITLE
Not practically install-able

### ISSUE THREAD

**Issue by AlainODea** [oktadeveloper/okta-aws-cli-assume-role#88]
The program is currently not really install-able.

Attempts to move it and its script into a bin directory on the PATH don't work as it needs **config.properties** in the current working directory.

Accepting properties from **~/.okta/config.properties** is one step in that direction. The Gradle application plugin is another option.

Either way, it would be useful for this to be install-able so it can be rolled out to a large team efficiently.

@smashling can you look into this?

**Comment by slancio** [comment]
I put config.properties, awscli and the jar file in the same folder, added that folder to my path and changed the contents of the script to this:

`cd "${BASH_SOURCE%/*}" || exit
java -classpath .:oktaawscli.jar com.okta.tools.awscli $@
`

Though it would be really great if the variables in config.properties would be looked for in the environment first and the file second and not require config.properties at all.

**Comment by AlainODea** [comment]
Cool stuff, @slancio! Would what I did in #92 work for you? It makes the config.properties optional and can load it from ~/.okta/ instead of PWD.

**Comment by slancio** [comment]
Generally, yes, but it's not really multi-user at that point (though I can't imagine that's a common use case) -- each user would have to have the JAR in their home directory in `~/.okta`, but the `awscli` command may end up somewhere that any user on a system can use it.

**Comment by AlainODea** [comment]
Sorry for the lack of clarity. Multi-user on a single system isn't the use-case I'm thinking of. I'm trying to solve rollout of the tool to ~200 distinct endpoints.

Don't forget to try `withokta` if you haven't yet ;) It lets you use this with arbitrary commands or scripts that use named AWS profiles.

For multiple users on a single system, it would be beneficial to be able to have it use a single JAR in a `%ProgramFiles%\Okta\` or `/usr/local/share/okta/` (or whatever `$PREFIX` makes sense for site-installed software) that all users could use. That would also make it possible to include this in a laptop image, so I may take a crack at solving that at some point.

There's a lot of room for improvement in what I've got here.
