### ISSUE TITLE
Unable to use latest release

### ISSUE THREAD

**Issue by shoekstra** [oktadeveloper/okta-aws-cli-assume-role#94]
Hi,

I was using an older version quite some time ago with success, I was able to run `./awscli`, get prompted for username and password, choose my okta role and then the AWS role policy I wanted to assume.  From there I was able to use the profile as expected (primary use is with Terraform) and assume roles in other accounts.

Since that version it looks like quite a bit has changed.

Now when running `awscli`, I no longer get prompted to assume a role policy, and when I run `./awscli sts get-caller-identity` a second time, I get:

```
Exception in thread "main" java.lang.NullPointerException
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:109)
        at com.okta.tools.awscli.main(awscli.java:31)
```

Is there something I'm missing?  I was getting the `not authorized to perform:
sts:AssumeRole on resource` but fixed that with the suggested inline policy.

**Comment by AlainODea** [comment]
This is a regression on **master**. Sorry about that.

This is the same issue as #95.

See my workaround here:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/95#issuecomment-370946716
