### ISSUE TITLE
Two AWS account token

### ISSUE THREAD

**Issue by satssin** [oktadeveloper/okta-aws-cli-assume-role#99]
I have a use case where I have two AWS accounts, one for prod and one for non-prod.
Both accounts are configured to talk to Okta.How can i use two Embed links in the config file to get temporary credentials from both the AWS accounts?

**Comment by smashling** [comment]
I created a profile store for this scenario, when multiple profiles are active at once. The command to use is [env OKTA_PROFILE=profilename ./withokta aws --profile profilename command]. running this for each profile will ask for the role for each from a list of available roles. Whenever these profiles are reused, the RoleArn is reused and the profile expiry is refreshed as long as the Okta session is valid.

**Comment by AlainODea** [comment]
@satssin you can’t embed two links. You need to follow the Okta AWS setup guidance for using multiple AWS accounts.

You could hack support for it by swapping in different versions of ~/.okta/config.properties. This could conceivably be done by making ~/.okta/ a Git repository and switching branches.

There is no intention of supporting this use case directly.

@mraible this can be closed.
